unit UCL.IconEditor;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Vcl.Grids, Vcl.ExtCtrls, Vcl.StdCtrls,
  System.UITypes, DesignEditors, DesignIntf, System.RegularExpressions;

type
  TFormIcons = class(TForm)
    GridIcons: TDrawGrid;
    PanelBottom: TPanel;
    EditIconCode: TEdit;
    LabelIconDescription: TLabel;
    ButtonOk: TButton;
    ButtonCancel: TButton;
    procedure ButtonCancelClick(Sender: TObject);
    procedure ButtonOkClick(Sender: TObject);
    procedure FormResize(Sender: TObject);
    procedure FormShow(Sender: TObject);
    procedure GridIconsClick(Sender: TObject);
    procedure GridIconsDblClick(Sender: TObject);
    procedure GridIconsDrawCell(Sender: TObject; ACol, ARow: Integer; Rect: TRect;
        State: TGridDrawState);
  private
    FIconCode: string;
    function FindIconIndex(const IconCode: string): Integer;
  public
    property IconCode: string read FIconCode write FIconCode;
  end;

 TSymbolCharProperty = class (TStringProperty)
 public
   function GetAttributes: TPropertyAttributes; override;
   procedure Edit; override;
   function GetValue: string; override;
   procedure SetValue(const Value: string); override;
 end;

//var
//  FormIcons: TFormIcons;

implementation

{$R *.dfm}

type
  TIconChar = record
    Id: string;
    Name: string;
  end;

{$REGION 'Segoe MDL2 Assets'}
const
  IconChars: array[0..1556] of TIconChar = (
(Id: 'E001'; Name: 'xxxx'),


(Id: 'E10B'; Name: 'Accept icon'),
(Id: 'E168'; Name: 'Account icon'),
(Id: 'E109'; Name: 'Add icon'),
(Id: 'E1E2'; Name: 'Add Friend icon'),
(Id: 'E1A7'; Name: 'Admin icon'),
(Id: 'E1A1'; Name: 'Align Center icon'),
(Id: 'E1A2'; Name: 'Align Left icon'),
(Id: 'E1A0'; Name: 'Align Right icon'),
(Id: 'E179'; Name: 'All Apps icon'),
(Id: 'E16C'; Name: 'Attach icon'),
(Id: 'E12D'; Name: 'Attach Camera icon'),
(Id: 'E189'; Name: 'Audio icon'),
(Id: 'E112'; Name: 'Back icon'),
(Id: 'E1D8'; Name: 'Back To Window icon'),
(Id: 'E1E0'; Name: 'Block Contact icon'),
(Id: 'E19B'; Name: 'Bold icon'),
(Id: 'E12F'; Name: 'Bookmarks icon'),
(Id: 'E155'; Name: 'Browse Photos icon'),
(Id: 'E133'; Name: 'Bullets icon'),
(Id: 'E1D0'; Name: 'Calculator icon'),
(Id: 'E163'; Name: 'Calendar icon'),
(Id: 'E161'; Name: 'Calendar Day icon'),
(Id: 'E1DB'; Name: 'Calendar Reply icon'),
(Id: 'E162'; Name: 'Calendar Week icon'),
(Id: 'E114'; Name: 'Camera icon'),
(Id: 'E10A'; Name: 'Cancel icon'),
(Id: 'E15A'; Name: 'Caption icon'),
(Id: 'E1C9'; Name: 'Cell Phone icon'),
(Id: 'E164'; Name: 'Character icon'),
(Id: 'E106'; Name: 'Clear icon'),
(Id: 'E1C5'; Name: 'Clear Selection icon'),
(Id: 'E121'; Name: 'Clock icon'),
(Id: 'E190'; Name: 'Closed Caption icon'),
(Id: 'E127'; Name: 'Close Pane icon'),
(Id: 'E134'; Name: 'Comment icon'),
(Id: 'E13D'; Name: 'Contact icon'),
(Id: 'E187'; Name: 'Contact 2 icon'),
(Id: 'E136'; Name: 'Contact Info icon'),
(Id: 'E181'; Name: 'Contact Presence icon'),
(Id: 'E16F'; Name: 'Copy icon'),
(Id: 'E123'; Name: 'Crop icon'),
(Id: 'E16B'; Name: 'Cut icon'),
(Id: 'E107'; Name: 'Delete icon'),
(Id: 'E1D1'; Name: 'Directions icon'),
(Id: 'E194'; Name: 'Disable Updates icon'),
(Id: 'E17A'; Name: 'Disconnect Drive icon'),
(Id: 'E19E'; Name: 'Dislike icon'),
(Id: 'E147'; Name: 'Dock Bottom icon'),
(Id: 'E145'; Name: 'Dock Left icon'),
(Id: 'E146'; Name: 'Dock Right icon'),
(Id: 'E130'; Name: 'Document icon'),
(Id: 'E118'; Name: 'Download icon'),
(Id: 'E104'; Name: 'Edit icon'),
(Id: 'E11D'; Name: 'Emoji icon'),
(Id: 'E170'; Name: 'Emoji 2 icon'),
(Id: 'E113'; Name: 'Favorite icon'),
(Id: 'E16E'; Name: 'Filter icon'),
(Id: 'E11A'; Name: 'Find icon'),
(Id: 'E129'; Name: 'Flag icon'),
(Id: 'E188'; Name: 'Folder icon'),
(Id: 'E185'; Name: 'Font icon'),
(Id: 'E186'; Name: 'Font Color icon'),
(Id: 'E1C6'; Name: 'Font Decrease icon'),
(Id: 'E1C7'; Name: 'Font Increase icon'),
(Id: 'E1C8'; Name: 'Font Size icon'),
(Id: 'E111'; Name: 'Forward icon'),
(Id: 'E1E9'; Name: 'Four Bars icon'),
(Id: 'E1D9'; Name: 'Full Screen icon'),
(Id: 'E700'; Name: 'GlobalNav icon'),
(Id: 'E12B'; Name: 'Globe icon'),
(Id: 'E143'; Name: 'Go icon'),
(Id: 'E1E4'; Name: 'Go To Start icon'),
(Id: 'E184'; Name: 'Go To Today icon'),
(Id: 'E137'; Name: 'Hang Up icon'),
(Id: 'E11B'; Name: 'Help icon'),
(Id: 'E16A'; Name: 'Hide BCC icon'),
(Id: 'E193'; Name: 'Highlight icon'),
(Id: 'E10F'; Name: 'Home icon'),
(Id: 'E150'; Name: 'Import icon'),
(Id: 'E151'; Name: 'Import All icon'),
(Id: 'E171'; Name: 'Important icon'),
(Id: 'E199'; Name: 'Italic icon'),
(Id: 'E144'; Name: 'Keyboard icon'),
(Id: 'E11F'; Name: 'Leave Chat icon'),
(Id: 'E1D3'; Name: 'Library icon'),
(Id: 'E19F'; Name: 'Like icon'),
(Id: 'E19D'; Name: 'Like Dislike icon'),
(Id: 'E167'; Name: 'Link icon'),
(Id: 'E14C'; Name: 'List icon'),
(Id: 'E119'; Name: 'Mail icon'),
(Id: 'E135'; Name: 'Mail Filled icon'),
(Id: 'E120'; Name: 'Mail Forward icon'),
(Id: 'E172'; Name: 'Mail Reply icon'),
(Id: 'E165'; Name: 'Mail Reply All icon'),
(Id: 'E178'; Name: 'Manage icon'),
(Id: 'E1C4'; Name: 'Map icon'),
(Id: 'E17B'; Name: 'Map Drive icon'),
(Id: 'E139'; Name: 'Map Pin icon'),
(Id: 'E1D5'; Name: 'Memo icon'),
(Id: 'E15F'; Name: 'Message icon'),
(Id: 'E1D6'; Name: 'Microphone icon'),
(Id: 'E10C'; Name: 'More icon'),
(Id: 'E19C'; Name: 'Move To Folder icon'),
(Id: 'E142'; Name: 'Music Info icon'),
(Id: 'E198'; Name: 'Mute icon'),
(Id: 'E1DA'; Name: 'New Folder icon'),
(Id: 'E17C'; Name: 'New Window icon'),
(Id: 'E101'; Name: 'Next icon'),
(Id: 'E1E6'; Name: 'One Bar icon'),
(Id: 'E1A5'; Name: 'Open File icon'),
(Id: 'E197'; Name: 'Open Local icon'),
(Id: 'E126'; Name: 'Open Pane icon'),
(Id: 'E17D'; Name: 'Open With icon'),
(Id: 'E14F'; Name: 'Orientation icon'),
(Id: 'E1A6'; Name: 'Other User icon'),
(Id: 'E1CE'; Name: 'Outline Star icon'),
(Id: 'E132'; Name: 'Page icon'),
(Id: 'E160'; Name: 'Page2 icon'),
(Id: 'E16D'; Name: 'Paste icon'),
(Id: 'E103'; Name: 'Pause icon'),
(Id: 'E125'; Name: 'People icon'),
(Id: 'E192'; Name: 'Permissions icon'),
(Id: 'E13A'; Name: 'Phone icon'),
(Id: 'E1D4'; Name: 'Phone Book icon'),
(Id: 'E158'; Name: 'Pictures icon'),
(Id: 'E141'; Name: 'Pin icon'),
(Id: 'E18A'; Name: 'Placeholder icon'),
(Id: 'E102'; Name: 'Play icon'),
(Id: 'E1D7'; Name: 'Post Update icon'),
(Id: 'E295'; Name: 'Preview icon'),
(Id: 'E12A'; Name: 'Preview Link icon'),
(Id: 'E100'; Name: 'Previous icon'),
(Id: 'E749'; Name: 'Print icon'),
(Id: 'E182'; Name: 'Priority icon'),
(Id: 'E131'; Name: 'Protected Document icon'),
(Id: 'E166'; Name: 'Read icon'),
(Id: 'E10D'; Name: 'Redo icon'),
(Id: 'E149'; Name: 'Refresh icon'),
(Id: 'E148'; Name: 'Remote icon'),
(Id: 'E108'; Name: 'Remove icon'),
(Id: 'E13E'; Name: 'Rename icon'),
(Id: 'E15E'; Name: 'Repair icon'),
(Id: 'E1CD'; Name: 'Repeat All icon'),
(Id: 'E1CC'; Name: 'Repeat 1 icon'),
(Id: 'E1DE'; Name: 'Report Hacked icon'),
(Id: 'E1CA'; Name: 'Reshare icon'),
(Id: 'E14A'; Name: 'Rotate icon'),
(Id: 'E124'; Name: 'Rotate Camera icon'),
(Id: 'E105'; Name: 'Save icon'),
(Id: 'E159'; Name: 'Save Local icon'),
(Id: 'E294'; Name: 'Scan icon'),
(Id: 'E14E'; Name: 'Select All icon'),
(Id: 'E122'; Name: 'Send icon'),
(Id: 'E18C'; Name: 'Set Lock Screen icon'),
(Id: 'E18D'; Name: 'Set Tile icon'),
(Id: 'E115'; Name: 'Setting icon'),
(Id: 'E72D'; Name: 'Share icon'),
(Id: 'E14D'; Name: 'Shop icon'),
(Id: 'E169'; Name: 'Show BCC icon'),
(Id: 'E15C'; Name: 'Show Results icon'),
(Id: 'E14B'; Name: 'Shuffle icon'),
(Id: 'E173'; Name: 'Slide Show icon'),
(Id: 'E1CF'; Name: 'Solid Star icon'),
(Id: 'E174'; Name: 'Sort icon'),
(Id: 'E15B'; Name: 'Stop icon'),
(Id: 'E191'; Name: 'Stop Slide Show icon'),
(Id: 'E1C3'; Name: 'Street icon'),
(Id: 'E13C'; Name: 'Switch icon'),
(Id: 'E1E1'; Name: 'Switch Apps  icon'),
(Id: 'E117'; Name: 'Sync icon'),
(Id: 'E1DF'; Name: 'Sync Folder icon'),
(Id: 'E1CB'; Name: 'Tag icon'),
(Id: 'E1D2'; Name: 'Target icon'),
(Id: 'E1E8'; Name: 'Three Bars icon'),
(Id: 'E1E3'; Name: 'Touch Pointer icon'),
(Id: 'E12C'; Name: 'Trim icon'),
(Id: 'E1E7'; Name: 'Two Bars icon'),
(Id: 'E11E'; Name: 'Two Page icon'),
(Id: 'E19A'; Name: 'Underline icon'),
(Id: 'E10E'; Name: 'Undo icon'),
(Id: 'E195'; Name: 'Unfavorite icon'),
(Id: 'E196'; Name: 'UnPin icon'),
(Id: 'E1DD'; Name: 'Unsync Folder icon'),
(Id: 'E110'; Name: 'Up icon'),
(Id: 'E11C'; Name: 'Upload icon'),
(Id: 'E116'; Name: 'Video icon'),
(Id: 'E13B'; Name: 'Video Chat icon'),
(Id: 'E18B'; Name: 'View icon'),
(Id: 'E138'; Name: 'View All icon'),
(Id: 'E15D'; Name: 'Volume icon'),
(Id: 'E156'; Name: 'Web Cam icon'),
(Id: 'E128'; Name: 'World icon'),
(Id: 'E990'; Name: 'Xbox icon'),
(Id: 'E1E5'; Name: 'Zero Bars icon'),
(Id: 'E1A3'; Name: 'Zoom icon'),
(Id: 'E12E'; Name: 'Zoom In icon'),
(Id: 'E1A4'; Name: 'Zoom Out icon'),

(Id: 'E700'; Name: 'GlobalNavigationButton'),
(Id: 'E701'; Name: 'Wifi'),
(Id: 'E702'; Name: 'Bluetooth'),
(Id: 'E703'; Name: 'Connect'),
(Id: 'E704'; Name: 'InternetSharing'),
(Id: 'E705'; Name: 'VPN'),
(Id: 'E706'; Name: 'Brightness'),
(Id: 'E707'; Name: 'MapPin'),
(Id: 'E708'; Name: 'QuietHours'),
(Id: 'E709'; Name: 'Airplane'),
(Id: 'E70A'; Name: 'Tablet'),
(Id: 'E70B'; Name: 'QuickNote'),
(Id: 'E70C'; Name: 'RememberedDevice'),
(Id: 'E70D'; Name: 'ChevronDown'),
(Id: 'E70E'; Name: 'ChevronUp'),
(Id: 'E70F'; Name: 'Edit'),
(Id: 'E710'; Name: 'Add'),
(Id: 'E711'; Name: 'Cancel'),
(Id: 'E712'; Name: 'More'),
(Id: 'E713'; Name: 'Settings'),
(Id: 'E714'; Name: 'Video'),
(Id: 'E715'; Name: 'Mail'),
(Id: 'E716'; Name: 'People'),
(Id: 'E717'; Name: 'Phone'),
(Id: 'E718'; Name: 'Pin'),
(Id: 'E719'; Name: 'Shop'),
(Id: 'E71A'; Name: 'Stop'),
(Id: 'E71B'; Name: 'Link'),
(Id: 'E71C'; Name: 'Filter'),
(Id: 'E71D'; Name: 'AllApps'),
(Id: 'E71E'; Name: 'Zoom'),
(Id: 'E71F'; Name: 'ZoomOut'),
(Id: 'E720'; Name: 'Microphone'),
(Id: 'E721'; Name: 'Search'),
(Id: 'E722'; Name: 'Camera'),
(Id: 'E723'; Name: 'Attach'),
(Id: 'E724'; Name: 'Send'),
(Id: 'E725'; Name: 'SendFill'),
(Id: 'E726'; Name: 'WalkSolid'),
(Id: 'E727'; Name: 'InPrivate'),
(Id: 'E728'; Name: 'FavoriteList'),
(Id: 'E729'; Name: 'PageSolid'),
(Id: 'E72A'; Name: 'Forward'),
(Id: 'E72B'; Name: 'Back'),
(Id: 'E72C'; Name: 'Refresh'),
(Id: 'E72D'; Name: 'Share'),
(Id: 'E72E'; Name: 'Lock'),
(Id: 'E730'; Name: 'ReportHacked'),
(Id: 'E731'; Name: 'EMI'),
(Id: 'E734'; Name: 'FavoriteStar'),
(Id: 'E735'; Name: 'FavoriteStarFill'),
(Id: 'E736'; Name: 'ReadingMode'),
(Id: 'E737'; Name: 'Favicon'),
(Id: 'E738'; Name: 'Remove'),
(Id: 'E739'; Name: 'Checkbox'),
(Id: 'E73A'; Name: 'CheckboxComposite'),
(Id: 'E73B'; Name: 'CheckboxFill'),
(Id: 'E73C'; Name: 'CheckboxIndeterminate'),
(Id: 'E73D'; Name: 'CheckboxCompositeReversed'),
(Id: 'E73E'; Name: 'CheckMark'),
(Id: 'E73F'; Name: 'BackToWindow'),
(Id: 'E740'; Name: 'FullScreen'),
(Id: 'E741'; Name: 'ResizeTouchLarger'),
(Id: 'E742'; Name: 'ResizeTouchSmaller'),
(Id: 'E743'; Name: 'ResizeMouseSmall'),
(Id: 'E744'; Name: 'ResizeMouseMedium'),
(Id: 'E745'; Name: 'ResizeMouseWide'),
(Id: 'E746'; Name: 'ResizeMouseTall'),
(Id: 'E747'; Name: 'ResizeMouseLarge'),
(Id: 'E748'; Name: 'SwitchUser'),
(Id: 'E749'; Name: 'Print'),
(Id: 'E74A'; Name: 'Up'),
(Id: 'E74B'; Name: 'Down'),
(Id: 'E74C'; Name: 'OEM'),
(Id: 'E74D'; Name: 'Delete'),
(Id: 'E74E'; Name: 'Save'),
(Id: 'E74F'; Name: 'Mute'),
(Id: 'E750'; Name: 'BackSpaceQWERTY'),
(Id: 'E751'; Name: 'ReturnKey'),
(Id: 'E752'; Name: 'UpArrowShiftKey'),
(Id: 'E753'; Name: 'Cloud'),
(Id: 'E754'; Name: 'Flashlight'),
(Id: 'E755'; Name: 'RotationLock'),
(Id: 'E756'; Name: 'CommandPrompt'),
(Id: 'E759'; Name: 'SIPMove'),
(Id: 'E75A'; Name: 'SIPUndock'),
(Id: 'E75B'; Name: 'SIPRedock'),
(Id: 'E75C'; Name: 'EraseTool'),
(Id: 'E75D'; Name: 'UnderscoreSpace'),
(Id: 'E75E'; Name: 'GripperTool'),
(Id: 'E75F'; Name: 'Dialpad'),
(Id: 'E760'; Name: 'PageLeft'),
(Id: 'E761'; Name: 'PageRight'),
(Id: 'E762'; Name: 'MultiSelect'),
(Id: 'E763'; Name: 'KeyboardLeftHanded'),
(Id: 'E764'; Name: 'KeyboardRightHanded'),
(Id: 'E765'; Name: 'KeyboardClassic'),
(Id: 'E766'; Name: 'KeyboardSplit'),
(Id: 'E767'; Name: 'Volume'),
(Id: 'E768'; Name: 'Play'),
(Id: 'E769'; Name: 'Pause'),
(Id: 'E76B'; Name: 'ChevronLeft'),
(Id: 'E76C'; Name: 'ChevronRight'),
(Id: 'E76D'; Name: 'InkingTool'),
(Id: 'E76E'; Name: 'Emoji2'),
(Id: 'E76F'; Name: 'GripperBarHorizontal'),
(Id: 'E770'; Name: 'System'),
(Id: 'E771'; Name: 'Personalize'),
(Id: 'E772'; Name: 'Devices'),
(Id: 'E773'; Name: 'SearchAndApps'),
(Id: 'E774'; Name: 'Globe'),
(Id: 'E775'; Name: 'TimeLanguage'),
(Id: 'E776'; Name: 'EaseOfAccess'),
(Id: 'E777'; Name: 'UpdateRestore'),
(Id: 'E778'; Name: 'HangUp'),
(Id: 'E779'; Name: 'ContactInfo'),
(Id: 'E77A'; Name: 'Unpin'),
(Id: 'E77B'; Name: 'Contact'),
(Id: 'E77C'; Name: 'Memo'),
(Id: 'E77E'; Name: 'IncomingCall'),
(Id: 'E77F'; Name: 'Paste'),
(Id: 'E780'; Name: 'PhoneBook'),
(Id: 'E781'; Name: 'LEDLight'),
(Id: 'E783'; Name: 'Error'),
(Id: 'E784'; Name: 'GripperBarVertical'),
(Id: 'E785'; Name: 'Unlock'),
(Id: 'E786'; Name: 'Slideshow'),
(Id: 'E787'; Name: 'Calendar'),
(Id: 'E788'; Name: 'GripperResize'),
(Id: 'E789'; Name: 'Megaphone'),
(Id: 'E78A'; Name: 'Trim'),
(Id: 'E78B'; Name: 'NewWindow'),
(Id: 'E78C'; Name: 'SaveLocal'),
(Id: 'E790'; Name: 'Color'),
(Id: 'E791'; Name: 'DataSense'),
(Id: 'E792'; Name: 'SaveAs'),
(Id: 'E793'; Name: 'Light'),
(Id: 'E799'; Name: 'AspectRatio'),
(Id: 'E7A5'; Name: 'DataSenseBar'),
(Id: 'E7A6'; Name: 'Redo'),
(Id: 'E7A7'; Name: 'Undo'),
(Id: 'E7A8'; Name: 'Crop'),
(Id: 'E7AC'; Name: 'OpenWith'),
(Id: 'E7AD'; Name: 'Rotate'),
(Id: 'E7B3'; Name: 'RedEye'),
(Id: 'E7B5'; Name: 'SetlockScreen'),
(Id: 'E7B7'; Name: 'MapPin2'),
(Id: 'E7B8'; Name: 'Package'),
(Id: 'E7BA'; Name: 'Warning'),
(Id: 'E7BC'; Name: 'ReadingList'),
(Id: 'E7BE'; Name: 'Education'),
(Id: 'E7BF'; Name: 'ShoppingCart'),
(Id: 'E7C0'; Name: 'Train'),
(Id: 'E7C1'; Name: 'Flag'),
(Id: 'E7C3'; Name: 'Page'),
(Id: 'E7C4'; Name: 'TaskView'),
(Id: 'E7C5'; Name: 'BrowsePhotos'),
(Id: 'E7C6'; Name: 'HalfStarLeft'),
(Id: 'E7C7'; Name: 'HalfStarRight'),
(Id: 'E7C8'; Name: 'Record'),
(Id: 'E7C9'; Name: 'TouchPointer'),
(Id: 'E7DE'; Name: 'LangJPN'),
(Id: 'E7E3'; Name: 'Ferry'),
(Id: 'E7E6'; Name: 'Highlight'),
(Id: 'E7E7'; Name: 'ActionCenterNotification'),
(Id: 'E7E8'; Name: 'PowerButton'),
(Id: 'E7EA'; Name: 'ResizeTouchNarrower'),
(Id: 'E7EB'; Name: 'ResizeTouchShorter'),
(Id: 'E7EC'; Name: 'DrivingMode'),
(Id: 'E7ED'; Name: 'RingerSilent'),
(Id: 'E7EE'; Name: 'OtherUser'),
(Id: 'E7EF'; Name: 'Admin'),
(Id: 'E7F0'; Name: 'CC'),
(Id: 'E7F1'; Name: 'SDCard'),
(Id: 'E7F2'; Name: 'CallForwarding'),
(Id: 'E7F3'; Name: 'SettingsDisplaySound'),
(Id: 'E7F4'; Name: 'TVMonitor'),
(Id: 'E7F5'; Name: 'Speakers'),
(Id: 'E7F6'; Name: 'Headphone'),
(Id: 'E7F7'; Name: 'DeviceLaptopPic'),
(Id: 'E7F8'; Name: 'DeviceLaptopNoPic'),
(Id: 'E7F9'; Name: 'DeviceMonitorRightPic'),
(Id: 'E7FA'; Name: 'DeviceMonitorLeftPic'),
(Id: 'E7FB'; Name: 'DeviceMonitorNoPic'),
(Id: 'E7FC'; Name: 'Game'),
(Id: 'E7FD'; Name: 'HorizontalTabKey'),
(Id: 'E802'; Name: 'StreetsideSplitMinimize'),
(Id: 'E803'; Name: 'StreetsideSplitExpand'),
(Id: 'E804'; Name: 'Car'),
(Id: 'E805'; Name: 'Walk'),
(Id: 'E806'; Name: 'Bus'),
(Id: 'E809'; Name: 'TiltUp'),
(Id: 'E80A'; Name: 'TiltDown'),
(Id: 'E80B'; Name: 'CallControl'),
(Id: 'E80C'; Name: 'RotateMapRight'),
(Id: 'E80D'; Name: 'RotateMapLeft'),
(Id: 'E80F'; Name: 'Home'),
(Id: 'E811'; Name: 'ParkingLocation'),
(Id: 'E812'; Name: 'MapCompassTop'),
(Id: 'E813'; Name: 'MapCompassBottom'),
(Id: 'E814'; Name: 'IncidentTriangle'),
(Id: 'E815'; Name: 'Touch'),
(Id: 'E816'; Name: 'MapDirections'),
(Id: 'E819'; Name: 'StartPoint'),
(Id: 'E81A'; Name: 'StopPoint'),
(Id: 'E81B'; Name: 'EndPoint'),
(Id: 'E81C'; Name: 'History'),
(Id: 'E81D'; Name: 'Location'),
(Id: 'E81E'; Name: 'MapLayers'),
(Id: 'E81F'; Name: 'Accident'),
(Id: 'E821'; Name: 'Work'),
(Id: 'E822'; Name: 'Construction'),
(Id: 'E823'; Name: 'Recent'),
(Id: 'E825'; Name: 'Bank'),
(Id: 'E826'; Name: 'DownloadMap'),
(Id: 'E829'; Name: 'InkingToolFill2'),
(Id: 'E82A'; Name: 'HighlightFill2'),
(Id: 'E82B'; Name: 'EraseToolFill'),
(Id: 'E82C'; Name: 'EraseToolFill2'),
(Id: 'E82D'; Name: 'Dictionary'),
(Id: 'E82E'; Name: 'DictionaryAdd'),
(Id: 'E82F'; Name: 'ToolTip'),
(Id: 'E830'; Name: 'ChromeBack'),
(Id: 'E835'; Name: 'ProvisioningPackage'),
(Id: 'E836'; Name: 'AddRemoteDevice'),
(Id: 'E838'; Name: 'FolderOpen'),
(Id: 'E839'; Name: 'Ethernet'),
(Id: 'E83A'; Name: 'ShareBroadband'),
(Id: 'E83B'; Name: 'DirectAccess'),
(Id: 'E83C'; Name: 'DialUp'),
(Id: 'E83D'; Name: 'DefenderApp'),
(Id: 'E83E'; Name: 'BatteryCharging9'),
(Id: 'E83F'; Name: 'Battery10'),
(Id: 'E840'; Name: 'Pinned'),
(Id: 'E841'; Name: 'PinFill'),
(Id: 'E842'; Name: 'PinnedFill'),
(Id: 'E843'; Name: 'PeriodKey'),
(Id: 'E844'; Name: 'PuncKey'),
(Id: 'E845'; Name: 'RevToggleKey'),
(Id: 'E846'; Name: 'RightArrowKeyTime1'),
(Id: 'E847'; Name: 'RightArrowKeyTime2'),
(Id: 'E848'; Name: 'LeftQuote'),
(Id: 'E849'; Name: 'RightQuote'),
(Id: 'E84A'; Name: 'DownShiftKey'),
(Id: 'E84B'; Name: 'UpShiftKey'),
(Id: 'E84C'; Name: 'PuncKey0'),
(Id: 'E84D'; Name: 'PuncKeyLeftBottom'),
(Id: 'E84E'; Name: 'RightArrowKeyTime3'),
(Id: 'E84F'; Name: 'RightArrowKeyTime4'),
(Id: 'E850'; Name: 'Battery0'),
(Id: 'E851'; Name: 'Battery1'),
(Id: 'E852'; Name: 'Battery2'),
(Id: 'E853'; Name: 'Battery3'),
(Id: 'E854'; Name: 'Battery4'),
(Id: 'E855'; Name: 'Battery5'),
(Id: 'E856'; Name: 'Battery6'),
(Id: 'E857'; Name: 'Battery7'),
(Id: 'E858'; Name: 'Battery8'),
(Id: 'E859'; Name: 'Battery9'),
(Id: 'E85A'; Name: 'BatteryCharging0'),
(Id: 'E85B'; Name: 'BatteryCharging1'),
(Id: 'E85C'; Name: 'BatteryCharging2'),
(Id: 'E85D'; Name: 'BatteryCharging3'),
(Id: 'E85E'; Name: 'BatteryCharging4'),
(Id: 'E85F'; Name: 'BatteryCharging5'),
(Id: 'E860'; Name: 'BatteryCharging6'),
(Id: 'E861'; Name: 'BatteryCharging7'),
(Id: 'E862'; Name: 'BatteryCharging8'),
(Id: 'E863'; Name: 'BatterySaver0'),
(Id: 'E864'; Name: 'BatterySaver1'),
(Id: 'E865'; Name: 'BatterySaver2'),
(Id: 'E866'; Name: 'BatterySaver3'),
(Id: 'E867'; Name: 'BatterySaver4'),
(Id: 'E868'; Name: 'BatterySaver5'),
(Id: 'E869'; Name: 'BatterySaver6'),
(Id: 'E86A'; Name: 'BatterySaver7'),
(Id: 'E86B'; Name: 'BatterySaver8'),
(Id: 'E86C'; Name: 'SignalBars1'),
(Id: 'E86D'; Name: 'SignalBars2'),
(Id: 'E86E'; Name: 'SignalBars3'),
(Id: 'E86F'; Name: 'SignalBars4'),
(Id: 'E870'; Name: 'SignalBars5'),
(Id: 'E871'; Name: 'SignalNotConnected'),
(Id: 'E872'; Name: 'Wifi1'),
(Id: 'E873'; Name: 'Wifi2'),
(Id: 'E874'; Name: 'Wifi3'),
(Id: 'E875'; Name: 'MobSIMLock'),
(Id: 'E876'; Name: 'MobSIMMissing'),
(Id: 'E877'; Name: 'Vibrate'),
(Id: 'E878'; Name: 'RoamingInternational'),
(Id: 'E879'; Name: 'RoamingDomestic'),
(Id: 'E87A'; Name: 'CallForwardInternational'),
(Id: 'E87B'; Name: 'CallForwardRoaming'),
(Id: 'E87C'; Name: 'JpnRomanji'),
(Id: 'E87D'; Name: 'JpnRomanjiLock'),
(Id: 'E87E'; Name: 'JpnRomanjiShift'),
(Id: 'E87F'; Name: 'JpnRomanjiShiftLock'),
(Id: 'E880'; Name: 'StatusDataTransfer'),
(Id: 'E881'; Name: 'StatusDataTransferVPN'),
(Id: 'E882'; Name: 'StatusDualSIM2'),
(Id: 'E883'; Name: 'StatusDualSIM2VPN'),
(Id: 'E884'; Name: 'StatusDualSIM1'),
(Id: 'E885'; Name: 'StatusDualSIM1VPN'),
(Id: 'E886'; Name: 'StatusSGLTE'),
(Id: 'E887'; Name: 'StatusSGLTECell'),
(Id: 'E888'; Name: 'StatusSGLTEDataVPN'),
(Id: 'E889'; Name: 'StatusVPN'),
(Id: 'E88A'; Name: 'WifiHotspot'),
(Id: 'E88B'; Name: 'LanguageKor'),
(Id: 'E88C'; Name: 'LanguageCht'),
(Id: 'E88D'; Name: 'LanguageChs'),
(Id: 'E88E'; Name: 'USB'),
(Id: 'E88F'; Name: 'InkingToolFill'),
(Id: 'E890'; Name: 'View'),
(Id: 'E891'; Name: 'HighlightFill'),
(Id: 'E892'; Name: 'Previous'),
(Id: 'E893'; Name: 'Next'),
(Id: 'E894'; Name: 'Clear'),
(Id: 'E895'; Name: 'Sync'),
(Id: 'E896'; Name: 'Download'),
(Id: 'E897'; Name: 'Help'),
(Id: 'E898'; Name: 'Upload'),
(Id: 'E899'; Name: 'Emoji'),
(Id: 'E89A'; Name: 'TwoPage'),
(Id: 'E89B'; Name: 'LeaveChat'),
(Id: 'E89C'; Name: 'MailForward'),
(Id: 'E89E'; Name: 'RotateCamera'),
(Id: 'E89F'; Name: 'ClosePane'),
(Id: 'E8A0'; Name: 'OpenPane'),
(Id: 'E8A1'; Name: 'PreviewLink'),
(Id: 'E8A2'; Name: 'AttachCamera'),
(Id: 'E8A3'; Name: 'ZoomIn'),
(Id: 'E8A4'; Name: 'Bookmarks'),
(Id: 'E8A5'; Name: 'Document'),
(Id: 'E8A6'; Name: 'ProtectedDocument'),
(Id: 'E8A7'; Name: 'OpenInNewWindow'),
(Id: 'E8A8'; Name: 'MailFill'),
(Id: 'E8A9'; Name: 'ViewAll'),
(Id: 'E8AA'; Name: 'VideoChat'),
(Id: 'E8AB'; Name: 'Switch'),
(Id: 'E8AC'; Name: 'Rename'),
(Id: 'E8AD'; Name: 'Go'),
(Id: 'E8AE'; Name: 'SurfaceHub'),
(Id: 'E8AF'; Name: 'Remote'),
(Id: 'E8B0'; Name: 'Click'),
(Id: 'E8B1'; Name: 'Shuffle'),
(Id: 'E8B2'; Name: 'Movies'),
(Id: 'E8B3'; Name: 'SelectAll'),
(Id: 'E8B4'; Name: 'Orientation'),
(Id: 'E8B5'; Name: 'Import'),
(Id: 'E8B6'; Name: 'ImportAll'),
(Id: 'E8B7'; Name: 'Folder'),
(Id: 'E8B8'; Name: 'Webcam'),
(Id: 'E8B9'; Name: 'Picture'),
(Id: 'E8BA'; Name: 'Caption'),
(Id: 'E8BB'; Name: 'ChromeClose'),
(Id: 'E8BC'; Name: 'ShowResults'),
(Id: 'E8BD'; Name: 'Message'),
(Id: 'E8BE'; Name: 'Leaf'),
(Id: 'E8BF'; Name: 'CalendarDay'),
(Id: 'E8C0'; Name: 'CalendarWeek'),
(Id: 'E8C1'; Name: 'Characters'),
(Id: 'E8C2'; Name: 'MailReplyAll'),
(Id: 'E8C3'; Name: 'Read'),
(Id: 'E8C4'; Name: 'ShowBcc'),
(Id: 'E8C5'; Name: 'HideBcc'),
(Id: 'E8C6'; Name: 'Cut'),
(Id: 'E8C7'; Name: 'PaymentCard'),
(Id: 'E8C8'; Name: 'Copy'),
(Id: 'E8C9'; Name: 'Important'),
(Id: 'E8CA'; Name: 'MailReply'),
(Id: 'E8CB'; Name: 'Sort'),
(Id: 'E8CC'; Name: 'MobileTablet'),
(Id: 'E8CD'; Name: 'DisconnectDrive'),
(Id: 'E8CE'; Name: 'MapDrive'),
(Id: 'E8CF'; Name: 'ContactPresence'),
(Id: 'E8D0'; Name: 'Priority'),
(Id: 'E8D1'; Name: 'GotoToday'),
(Id: 'E8D2'; Name: 'Font'),
(Id: 'E8D3'; Name: 'FontColor'),
(Id: 'E8D4'; Name: 'Contact2'),
(Id: 'E8D5'; Name: 'FolderFill'),
(Id: 'E8D6'; Name: 'Audio'),
(Id: 'E8D7'; Name: 'Permissions'),
(Id: 'E8D8'; Name: 'DisableUpdates'),
(Id: 'E8D9'; Name: 'Unfavorite'),
(Id: 'E8DA'; Name: 'OpenLocal'),
(Id: 'E8DB'; Name: 'Italic'),
(Id: 'E8DC'; Name: 'Underline'),
(Id: 'E8DD'; Name: 'Bold'),
(Id: 'E8DE'; Name: 'MoveToFolder'),
(Id: 'E8DF'; Name: 'LikeDislike'),
(Id: 'E8E0'; Name: 'Dislike'),
(Id: 'E8E1'; Name: 'Like'),
(Id: 'E8E2'; Name: 'AlignRight'),
(Id: 'E8E3'; Name: 'AlignCenter'),
(Id: 'E8E4'; Name: 'AlignLeft'),
(Id: 'E8E5'; Name: 'OpenFile'),
(Id: 'E8E6'; Name: 'ClearSelection'),
(Id: 'E8E7'; Name: 'FontDecrease'),
(Id: 'E8E8'; Name: 'FontIncrease'),
(Id: 'E8E9'; Name: 'FontSize'),
(Id: 'E8EA'; Name: 'CellPhone'),
(Id: 'E8EB'; Name: 'Reshare'),
(Id: 'E8EC'; Name: 'Tag'),
(Id: 'E8ED'; Name: 'RepeatOne'),
(Id: 'E8EE'; Name: 'RepeatAll'),
(Id: 'E8EF'; Name: 'Calculator'),
(Id: 'E8F0'; Name: 'Directions'),
(Id: 'E8F1'; Name: 'Library'),
(Id: 'E8F2'; Name: 'ChatBubbles'),
(Id: 'E8F3'; Name: 'PostUpdate'),
(Id: 'E8F4'; Name: 'NewFolder'),
(Id: 'E8F5'; Name: 'CalendarReply'),
(Id: 'E8F6'; Name: 'UnsyncFolder'),
(Id: 'E8F7'; Name: 'SyncFolder'),
(Id: 'E8F8'; Name: 'BlockContact'),
(Id: 'E8F9'; Name: 'SwitchApps'),
(Id: 'E8FA'; Name: 'AddFriend'),
(Id: 'E8FB'; Name: 'Accept'),
(Id: 'E8FC'; Name: 'GoToStart'),
(Id: 'E8FD'; Name: 'BulletedList'),
(Id: 'E8FE'; Name: 'Scan'),
(Id: 'E8FF'; Name: 'Preview'),
(Id: 'E902'; Name: 'Group'),
(Id: 'E904'; Name: 'ZeroBars'),
(Id: 'E905'; Name: 'OneBar'),
(Id: 'E906'; Name: 'TwoBars'),
(Id: 'E907'; Name: 'ThreeBars'),
(Id: 'E908'; Name: 'FourBars'),
(Id: 'E909'; Name: 'World'),
(Id: 'E90A'; Name: 'Comment'),
(Id: 'E90B'; Name: 'MusicInfo'),
(Id: 'E90C'; Name: 'DockLeft'),
(Id: 'E90D'; Name: 'DockRight'),
(Id: 'E90E'; Name: 'DockBottom'),
(Id: 'E90F'; Name: 'Repair'),
(Id: 'E910'; Name: 'Accounts'),
(Id: 'E911'; Name: 'DullSound'),
(Id: 'E912'; Name: 'Manage'),
(Id: 'E913'; Name: 'Street'),
(Id: 'E914'; Name: 'Printer3D'),
(Id: 'E915'; Name: 'RadioBullet'),
(Id: 'E916'; Name: 'Stopwatch'),
(Id: 'E91B'; Name: 'Photo'),
(Id: 'E91C'; Name: 'ActionCenter'),
(Id: 'E91F'; Name: 'FullCircleMask'),
(Id: 'E921'; Name: 'ChromeMinimize'),
(Id: 'E922'; Name: 'ChromeMaximize'),
(Id: 'E923'; Name: 'ChromeRestore'),
(Id: 'E924'; Name: 'Annotation'),
(Id: 'E925'; Name: 'BackSpaceQWERTYSm'),
(Id: 'E926'; Name: 'BackSpaceQWERTYMd'),
(Id: 'E927'; Name: 'Swipe'),
(Id: 'E928'; Name: 'Fingerprint'),
(Id: 'E929'; Name: 'Handwriting'),
(Id: 'E92C'; Name: 'ChromeBackToWindow'),
(Id: 'E92D'; Name: 'ChromeFullScreen'),
(Id: 'E92E'; Name: 'KeyboardStandard'),
(Id: 'E92F'; Name: 'KeyboardDismiss'),
(Id: 'E930'; Name: 'Completed'),
(Id: 'E931'; Name: 'ChromeAnnotate'),
(Id: 'E932'; Name: 'Label'),
(Id: 'E933'; Name: 'IBeam'),
(Id: 'E934'; Name: 'IBeamOutline'),
(Id: 'E935'; Name: 'FlickDown'),
(Id: 'E936'; Name: 'FlickUp'),
(Id: 'E937'; Name: 'FlickLeft'),
(Id: 'E938'; Name: 'FlickRight'),
(Id: 'E939'; Name: 'FeedbackApp'),
(Id: 'E93C'; Name: 'MusicAlbum'),
(Id: 'E93E'; Name: 'Streaming'),
(Id: 'E943'; Name: 'Code'),
(Id: 'E944'; Name: 'ReturnToWindow'),
(Id: 'E945'; Name: 'LightningBolt'),
(Id: 'E946'; Name: 'Info'),
(Id: 'E947'; Name: 'CalculatorMultiply'),
(Id: 'E948'; Name: 'CalculatorAddition'),
(Id: 'E949'; Name: 'CalculatorSubtract'),
(Id: 'E94A'; Name: 'CalculatorDivide'),
(Id: 'E94B'; Name: 'CalculatorSquareroot'),
(Id: 'E94C'; Name: 'CalculatorPercentage'),
(Id: 'E94D'; Name: 'CalculatorNegate'),
(Id: 'E94E'; Name: 'CalculatorEqualTo'),
(Id: 'E94F'; Name: 'CalculatorBackspace'),
(Id: 'E950'; Name: 'Component'),
(Id: 'E951'; Name: 'DMC'),
(Id: 'E952'; Name: 'Dock'),
(Id: 'E953'; Name: 'MultimediaDMS'),
(Id: 'E954'; Name: 'MultimediaDVR'),
(Id: 'E955'; Name: 'MultimediaPMP'),
(Id: 'E956'; Name: 'PrintfaxPrinterFile'),
(Id: 'E957'; Name: 'Sensor'),
(Id: 'E958'; Name: 'StorageOptical'),
(Id: 'E95A'; Name: 'Communications'),
(Id: 'E95B'; Name: 'Headset'),
(Id: 'E95D'; Name: 'Projector'),
(Id: 'E95E'; Name: 'Health'),
(Id: 'E95F'; Name: 'Wire'),
(Id: 'E960'; Name: 'Webcam2'),
(Id: 'E961'; Name: 'Input'),
(Id: 'E962'; Name: 'Mouse'),
(Id: 'E963'; Name: 'Smartcard'),
(Id: 'E964'; Name: 'SmartcardVirtual'),
(Id: 'E965'; Name: 'MediaStorageTower'),
(Id: 'E966'; Name: 'ReturnKeySm'),
(Id: 'E967'; Name: 'GameConsole'),
(Id: 'E968'; Name: 'Network'),
(Id: 'E969'; Name: 'StorageNetworkWireless'),
(Id: 'E96A'; Name: 'StorageTape'),
(Id: 'E96D'; Name: 'ChevronUpSmall'),
(Id: 'E96E'; Name: 'ChevronDownSmall'),
(Id: 'E96F'; Name: 'ChevronLeftSmall'),
(Id: 'E970'; Name: 'ChevronRightSmall'),
(Id: 'E971'; Name: 'ChevronUpMed'),
(Id: 'E972'; Name: 'ChevronDownMed'),
(Id: 'E973'; Name: 'ChevronLeftMed'),
(Id: 'E974'; Name: 'ChevronRightMed'),
(Id: 'E975'; Name: 'Devices2'),
(Id: 'E976'; Name: 'ExpandTile'),
(Id: 'E977'; Name: 'PC1'),
(Id: 'E978'; Name: 'PresenceChicklet'),
(Id: 'E979'; Name: 'PresenceChickletVideo'),
(Id: 'E97A'; Name: 'Reply'),
(Id: 'E97B'; Name: 'SetTile'),
(Id: 'E97C'; Name: 'Type'),
(Id: 'E97D'; Name: 'Korean'),
(Id: 'E97E'; Name: 'HalfAlpha'),
(Id: 'E97F'; Name: 'FullAlpha'),
(Id: 'E980'; Name: 'Key12On'),
(Id: 'E981'; Name: 'ChineseChangjie'),
(Id: 'E982'; Name: 'QWERTYOn'),
(Id: 'E983'; Name: 'QWERTYOff'),
(Id: 'E984'; Name: 'ChineseQuick'),
(Id: 'E985'; Name: 'Japanese'),
(Id: 'E986'; Name: 'FullHiragana'),
(Id: 'E987'; Name: 'FullKatakana'),
(Id: 'E988'; Name: 'HalfKatakana'),
(Id: 'E989'; Name: 'ChineseBoPoMoFo'),
(Id: 'E98A'; Name: 'ChinesePinyin'),
(Id: 'E98F'; Name: 'ConstructionCone'),
(Id: 'E990'; Name: 'XboxOneConsole'),
(Id: 'E992'; Name: 'Volume0'),
(Id: 'E993'; Name: 'Volume1'),
(Id: 'E994'; Name: 'Volume2'),
(Id: 'E995'; Name: 'Volume3'),
(Id: 'E996'; Name: 'BatteryUnknown'),
(Id: 'E998'; Name: 'WifiAttentionOverlay'),
(Id: 'E99A'; Name: 'Robot'),
(Id: 'E9A1'; Name: 'TapAndSend'),
(Id: 'E9A6'; Name: 'FitPage'),
(Id: 'E9A8'; Name: 'PasswordKeyShow'),
(Id: 'E9A9'; Name: 'PasswordKeyHide'),
(Id: 'E9AA'; Name: 'BidiLtr'),
(Id: 'E9AB'; Name: 'BidiRtl'),
(Id: 'E9AC'; Name: 'ForwardSm'),
(Id: 'E9AD'; Name: 'CommaKey'),
(Id: 'E9AE'; Name: 'DashKey'),
(Id: 'E9AF'; Name: 'DullSoundKey'),
(Id: 'E9B0'; Name: 'HalfDullSound'),
(Id: 'E9B1'; Name: 'RightDoubleQuote'),
(Id: 'E9B2'; Name: 'LeftDoubleQuote'),
(Id: 'E9B3'; Name: 'PuncKeyRightBottom'),
(Id: 'E9B4'; Name: 'PuncKey1'),
(Id: 'E9B5'; Name: 'PuncKey2'),
(Id: 'E9B6'; Name: 'PuncKey3'),
(Id: 'E9B7'; Name: 'PuncKey4'),
(Id: 'E9B8'; Name: 'PuncKey5'),
(Id: 'E9B9'; Name: 'PuncKey6'),
(Id: 'E9BA'; Name: 'PuncKey9'),
(Id: 'E9BB'; Name: 'PuncKey7'),
(Id: 'E9BC'; Name: 'PuncKey8'),
(Id: 'E9CA'; Name: 'Frigid'),
(Id: 'E9CE'; Name: 'Unknown'),
(Id: 'E9D2'; Name: 'AreaChart'),
(Id: 'E9D5'; Name: 'CheckList'),
(Id: 'E9D9'; Name: 'Diagnostic'),
(Id: 'E9E9'; Name: 'Equalizer'),
(Id: 'E9F3'; Name: 'Process'),
(Id: 'E9F5'; Name: 'Processing'),
(Id: 'E9F9'; Name: 'ReportDocument'),
(Id: 'EA0C'; Name: 'VideoSolid'),
(Id: 'EA0D'; Name: 'MixedMediaBadge'),
(Id: 'EA14'; Name: 'DisconnectDisplay'),
(Id: 'EA18'; Name: 'Shield'),
(Id: 'EA1F'; Name: 'Info2'),
(Id: 'EA21'; Name: 'ActionCenterAsterisk'),
(Id: 'EA24'; Name: 'Beta'),
(Id: 'EA35'; Name: 'SaveCopy'),
(Id: 'EA37'; Name: 'List'),
(Id: 'EA38'; Name: 'Asterisk'),
(Id: 'EA39'; Name: 'ErrorBadge'),
(Id: 'EA3A'; Name: 'CircleRing'),
(Id: 'EA3B'; Name: 'CircleFill'),
(Id: 'EA3C'; Name: 'MergeCall'),
(Id: 'EA3D'; Name: 'PrivateCall'),
(Id: 'EA3F'; Name: 'Record2'),
(Id: 'EA40'; Name: 'AllAppsMirrored'),
(Id: 'EA41'; Name: 'BookmarksMirrored'),
(Id: 'EA42'; Name: 'BulletedListMirrored'),
(Id: 'EA43'; Name: 'CallForwardInternationalMirrored'),
(Id: 'EA44'; Name: 'CallForwardRoamingMirrored'),
(Id: 'EA47'; Name: 'ChromeBackMirrored'),
(Id: 'EA48'; Name: 'ClearSelectionMirrored'),
(Id: 'EA49'; Name: 'ClosePaneMirrored'),
(Id: 'EA4A'; Name: 'ContactInfoMirrored'),
(Id: 'EA4B'; Name: 'DockRightMirrored'),
(Id: 'EA4C'; Name: 'DockLeftMirrored'),
(Id: 'EA4E'; Name: 'ExpandTileMirrored'),
(Id: 'EA4F'; Name: 'GoMirrored'),
(Id: 'EA50'; Name: 'GripperResizeMirrored'),
(Id: 'EA51'; Name: 'HelpMirrored'),
(Id: 'EA52'; Name: 'ImportMirrored'),
(Id: 'EA53'; Name: 'ImportAllMirrored'),
(Id: 'EA54'; Name: 'LeaveChatMirrored'),
(Id: 'EA55'; Name: 'ListMirrored'),
(Id: 'EA56'; Name: 'MailForwardMirrored'),
(Id: 'EA57'; Name: 'MailReplyMirrored'),
(Id: 'EA58'; Name: 'MailReplyAllMirrored'),
(Id: 'EA5B'; Name: 'OpenPaneMirrored'),
(Id: 'EA5C'; Name: 'OpenWithMirrored'),
(Id: 'EA5E'; Name: 'ParkingLocationMirrored'),
(Id: 'EA5F'; Name: 'ResizeMouseMediumMirrored'),
(Id: 'EA60'; Name: 'ResizeMouseSmallMirrored'),
(Id: 'EA61'; Name: 'ResizeMouseTallMirrored'),
(Id: 'EA62'; Name: 'ResizeTouchNarrowerMirrored'),
(Id: 'EA63'; Name: 'SendMirrored'),
(Id: 'EA64'; Name: 'SendFillMirrored'),
(Id: 'EA65'; Name: 'ShowResultsMirrored'),
(Id: 'EA69'; Name: 'Media'),
(Id: 'EA6A'; Name: 'SyncError'),
(Id: 'EA6C'; Name: 'Devices3'),
(Id: 'EA79'; Name: 'SlowMotionOn'),
(Id: 'EA80'; Name: 'Lightbulb'),
(Id: 'EA81'; Name: 'StatusCircle'),
(Id: 'EA82'; Name: 'StatusTriangle'),
(Id: 'EA83'; Name: 'StatusError'),
(Id: 'EA84'; Name: 'StatusWarning'),
(Id: 'EA86'; Name: 'Puzzle'),
(Id: 'EA89'; Name: 'CalendarSolid'),
(Id: 'EA8A'; Name: 'HomeSolid'),
(Id: 'EA8B'; Name: 'ParkingLocationSolid'),
(Id: 'EA8C'; Name: 'ContactSolid'),
(Id: 'EA8D'; Name: 'ConstructionSolid'),
(Id: 'EA8E'; Name: 'AccidentSolid'),
(Id: 'EA8F'; Name: 'Ringer'),
(Id: 'EA90'; Name: 'PDF'),
(Id: 'EA91'; Name: 'ThoughtBubble'),
(Id: 'EA92'; Name: 'HeartBroken'),
(Id: 'EA93'; Name: 'BatteryCharging10'),
(Id: 'EA94'; Name: 'BatterySaver9'),
(Id: 'EA95'; Name: 'BatterySaver10'),
(Id: 'EA97'; Name: 'CallForwardingMirrored'),
(Id: 'EA98'; Name: 'MultiSelectMirrored'),
(Id: 'EA99'; Name: 'Broom'),
(Id: 'EAC2'; Name: 'ForwardCall'),
(Id: 'EADF'; Name: 'Trackers'),
(Id: 'EAFC'; Name: 'Market'),
(Id: 'EB05'; Name: 'PieSingle'),
(Id: 'EB0F'; Name: 'StockDown'),
(Id: 'EB11'; Name: 'StockUp'),
(Id: 'EB3C'; Name: 'Design'),
(Id: 'EB41'; Name: 'Website'),
(Id: 'EB42'; Name: 'Drop'),
(Id: 'EB44'; Name: 'Radar'),
(Id: 'EB47'; Name: 'BusSolid'),
(Id: 'EB48'; Name: 'FerrySolid'),
(Id: 'EB49'; Name: 'StartPointSolid'),
(Id: 'EB4A'; Name: 'StopPointSolid'),
(Id: 'EB4B'; Name: 'EndPointSolid'),
(Id: 'EB4C'; Name: 'AirplaneSolid'),
(Id: 'EB4D'; Name: 'TrainSolid'),
(Id: 'EB4E'; Name: 'WorkSolid'),
(Id: 'EB4F'; Name: 'ReminderFill'),
(Id: 'EB50'; Name: 'Reminder'),
(Id: 'EB51'; Name: 'Heart'),
(Id: 'EB52'; Name: 'HeartFill'),
(Id: 'EB55'; Name: 'EthernetError'),
(Id: 'EB56'; Name: 'EthernetWarning'),
(Id: 'EB57'; Name: 'StatusConnecting1'),
(Id: 'EB58'; Name: 'StatusConnecting2'),
(Id: 'EB59'; Name: 'StatusUnsecure'),
(Id: 'EB5A'; Name: 'WifiError0'),
(Id: 'EB5B'; Name: 'WifiError1'),
(Id: 'EB5C'; Name: 'WifiError2'),
(Id: 'EB5D'; Name: 'WifiError3'),
(Id: 'EB5E'; Name: 'WifiError4'),
(Id: 'EB5F'; Name: 'WifiWarning0'),
(Id: 'EB60'; Name: 'WifiWarning1'),
(Id: 'EB61'; Name: 'WifiWarning2'),
(Id: 'EB62'; Name: 'WifiWarning3'),
(Id: 'EB63'; Name: 'WifiWarning4'),
(Id: 'EB66'; Name: 'Devices4'),
(Id: 'EB67'; Name: 'NUIIris'),
(Id: 'EB68'; Name: 'NUIFace'),
(Id: 'EB7E'; Name: 'EditMirrored'),
(Id: 'EB82'; Name: 'NUIFPStartSlideHand'),
(Id: 'EB83'; Name: 'NUIFPStartSlideAction'),
(Id: 'EB84'; Name: 'NUIFPContinueSlideHand'),
(Id: 'EB85'; Name: 'NUIFPContinueSlideAction'),
(Id: 'EB86'; Name: 'NUIFPRollRightHand'),
(Id: 'EB87'; Name: 'NUIFPRollRightHandAction'),
(Id: 'EB88'; Name: 'NUIFPRollLeftHand'),
(Id: 'EB89'; Name: 'NUIFPRollLeftAction'),
(Id: 'EB8A'; Name: 'NUIFPPressHand'),
(Id: 'EB8B'; Name: 'NUIFPPressAction'),
(Id: 'EB8C'; Name: 'NUIFPPressRepeatHand'),
(Id: 'EB8D'; Name: 'NUIFPPressRepeatAction'),
(Id: 'EB90'; Name: 'StatusErrorFull'),
(Id: 'EB91'; Name: 'TaskViewExpanded'),
(Id: 'EB95'; Name: 'Certificate'),
(Id: 'EB96'; Name: 'BackSpaceQWERTYLg'),
(Id: 'EB97'; Name: 'ReturnKeyLg'),
(Id: 'EB9D'; Name: 'FastForward'),
(Id: 'EB9E'; Name: 'Rewind'),
(Id: 'EB9F'; Name: 'Photo2'),
(Id: 'EBA0'; Name: 'MobBattery0'),
(Id: 'EBA1'; Name: 'MobBattery1'),
(Id: 'EBA2'; Name: 'MobBattery2'),
(Id: 'EBA3'; Name: 'MobBattery3'),
(Id: 'EBA4'; Name: 'MobBattery4'),
(Id: 'EBA5'; Name: 'MobBattery5'),
(Id: 'EBA6'; Name: 'MobBattery6'),
(Id: 'EBA7'; Name: 'MobBattery7'),
(Id: 'EBA8'; Name: 'MobBattery8'),
(Id: 'EBA9'; Name: 'MobBattery9'),
(Id: 'EBAA'; Name: 'MobBattery10'),
(Id: 'EBAB'; Name: 'MobBatteryCharging0'),
(Id: 'EBAC'; Name: 'MobBatteryCharging1'),
(Id: 'EBAD'; Name: 'MobBatteryCharging2'),
(Id: 'EBAE'; Name: 'MobBatteryCharging3'),
(Id: 'EBAF'; Name: 'MobBatteryCharging4'),
(Id: 'EBB0'; Name: 'MobBatteryCharging5'),
(Id: 'EBB1'; Name: 'MobBatteryCharging6'),
(Id: 'EBB2'; Name: 'MobBatteryCharging7'),
(Id: 'EBB3'; Name: 'MobBatteryCharging8'),
(Id: 'EBB4'; Name: 'MobBatteryCharging9'),
(Id: 'EBB5'; Name: 'MobBatteryCharging10'),
(Id: 'EBB6'; Name: 'MobBatterySaver0'),
(Id: 'EBB7'; Name: 'MobBatterySaver1'),
(Id: 'EBB8'; Name: 'MobBatterySaver2'),
(Id: 'EBB9'; Name: 'MobBatterySaver3'),
(Id: 'EBBA'; Name: 'MobBatterySaver4'),
(Id: 'EBBB'; Name: 'MobBatterySaver5'),
(Id: 'EBBC'; Name: 'MobBatterySaver6'),
(Id: 'EBBD'; Name: 'MobBatterySaver7'),
(Id: 'EBBE'; Name: 'MobBatterySaver8'),
(Id: 'EBBF'; Name: 'MobBatterySaver9'),
(Id: 'EBC0'; Name: 'MobBatterySaver10'),
(Id: 'EBC3'; Name: 'DictionaryCloud'),
(Id: 'EBC4'; Name: 'ResetDrive'),
(Id: 'EBC5'; Name: 'VolumeBars'),
(Id: 'EBC6'; Name: 'Project'),
(Id: 'EBD2'; Name: 'AdjustHologram'),
(Id: 'EBD4'; Name: 'WifiCallBars'),
(Id: 'EBD5'; Name: 'WifiCall0'),
(Id: 'EBD6'; Name: 'WifiCall1'),
(Id: 'EBD7'; Name: 'WifiCall2'),
(Id: 'EBD8'; Name: 'WifiCall3'),
(Id: 'EBD9'; Name: 'WifiCall4'),
(Id: 'EBDA'; Name: 'Family'),
(Id: 'EBDB'; Name: 'LockFeedback'),
(Id: 'EBDE'; Name: 'DeviceDiscovery'),
(Id: 'EBE6'; Name: 'WindDirection'),
(Id: 'EBE7'; Name: 'RightArrowKeyTime0'),
(Id: 'EBE8'; Name: 'Bug'),
(Id: 'EBFC'; Name: 'TabletMode'),
(Id: 'EBFD'; Name: 'StatusCircleLeft'),
(Id: 'EBFE'; Name: 'StatusTriangleLeft'),
(Id: 'EBFF'; Name: 'StatusErrorLeft'),
(Id: 'EC00'; Name: 'StatusWarningLeft'),
(Id: 'EC02'; Name: 'MobBatteryUnknown'),
(Id: 'EC05'; Name: 'NetworkTower'),
(Id: 'EC06'; Name: 'CityNext'),
(Id: 'EC07'; Name: 'CityNext2'),
(Id: 'EC08'; Name: 'Courthouse'),
(Id: 'EC09'; Name: 'Groceries'),
(Id: 'EC0A'; Name: 'Sustainable'),
(Id: 'EC0B'; Name: 'BuildingEnergy'),
(Id: 'EC11'; Name: 'ToggleFilled'),
(Id: 'EC12'; Name: 'ToggleBorder'),
(Id: 'EC13'; Name: 'SliderThumb'),
(Id: 'EC14'; Name: 'ToggleThumb'),
(Id: 'EC15'; Name: 'MiracastLogoSmall'),
(Id: 'EC16'; Name: 'MiracastLogoLarge'),
(Id: 'EC19'; Name: 'PLAP'),
(Id: 'EC1B'; Name: 'Badge'),
(Id: 'EC1E'; Name: 'SignalRoaming'),
(Id: 'EC20'; Name: 'MobileLocked'),
(Id: 'EC24'; Name: 'InsiderHubApp'),
(Id: 'EC25'; Name: 'PersonalFolder'),
(Id: 'EC26'; Name: 'HomeGroup'),
(Id: 'EC27'; Name: 'MyNetwork'),
(Id: 'EC31'; Name: 'KeyboardFull'),
(Id: 'EC32'; Name: 'Cafe'),
(Id: 'EC37'; Name: 'MobSignal1'),
(Id: 'EC38'; Name: 'MobSignal2'),
(Id: 'EC39'; Name: 'MobSignal3'),
(Id: 'EC3A'; Name: 'MobSignal4'),
(Id: 'EC3B'; Name: 'MobSignal5'),
(Id: 'EC3C'; Name: 'MobWifi1'),
(Id: 'EC3D'; Name: 'MobWifi2'),
(Id: 'EC3E'; Name: 'MobWifi3'),
(Id: 'EC3F'; Name: 'MobWifi4'),
(Id: 'EC40'; Name: 'MobAirplane'),
(Id: 'EC41'; Name: 'MobBluetooth'),
(Id: 'EC42'; Name: 'MobActionCenter'),
(Id: 'EC43'; Name: 'MobLocation'),
(Id: 'EC44'; Name: 'MobWifiHotspot'),
(Id: 'EC45'; Name: 'LanguageJpn'),
(Id: 'EC46'; Name: 'MobQuietHours'),
(Id: 'EC47'; Name: 'MobDrivingMode'),
(Id: 'EC48'; Name: 'SpeedOff'),
(Id: 'EC49'; Name: 'SpeedMedium'),
(Id: 'EC4A'; Name: 'SpeedHigh'),
(Id: 'EC4E'; Name: 'ThisPC'),
(Id: 'EC4F'; Name: 'MusicNote'),
(Id: 'EC50'; Name: 'FileExplorer'),
(Id: 'EC51'; Name: 'FileExplorerApp'),
(Id: 'EC52'; Name: 'LeftArrowKeyTime0'),
(Id: 'EC54'; Name: 'MicOff'),
(Id: 'EC55'; Name: 'MicSleep'),
(Id: 'EC56'; Name: 'MicError'),
(Id: 'EC57'; Name: 'PlaybackRate1x'),
(Id: 'EC58'; Name: 'PlaybackRateOther'),
(Id: 'EC59'; Name: 'CashDrawer'),
(Id: 'EC5A'; Name: 'BarcodeScanner'),
(Id: 'EC5B'; Name: 'ReceiptPrinter'),
(Id: 'EC5C'; Name: 'MagStripeReader'),
(Id: 'EC61'; Name: 'CompletedSolid'),
(Id: 'EC64'; Name: 'CompanionApp'),
(Id: 'EC6C'; Name: 'Favicon2'),
(Id: 'EC6D'; Name: 'SwipeRevealArt'),
(Id: 'EC71'; Name: 'MicOn'),
(Id: 'EC72'; Name: 'MicClipping'),
(Id: 'EC74'; Name: 'TabletSelected'),
(Id: 'EC75'; Name: 'MobileSelected'),
(Id: 'EC76'; Name: 'LaptopSelected'),
(Id: 'EC77'; Name: 'TVMonitorSelected'),
(Id: 'EC7A'; Name: 'DeveloperTools'),
(Id: 'EC7E'; Name: 'MobCallForwarding'),
(Id: 'EC7F'; Name: 'MobCallForwardingMirrored'),
(Id: 'EC80'; Name: 'BodyCam'),
(Id: 'EC81'; Name: 'PoliceCar'),
(Id: 'EC87'; Name: 'Draw'),
(Id: 'EC88'; Name: 'DrawSolid'),
(Id: 'EC8A'; Name: 'LowerBrightness'),
(Id: 'EC8F'; Name: 'ScrollUpDown'),
(Id: 'EC92'; Name: 'DateTime'),
(Id: 'ECA5'; Name: 'Tiles'),
(Id: 'ECA7'; Name: 'PartyLeader'),
(Id: 'ECAA'; Name: 'AppIconDefault'),
(Id: 'ECAD'; Name: 'Calories'),
(Id: 'ECB9'; Name: 'BandBattery0'),
(Id: 'ECBA'; Name: 'BandBattery1'),
(Id: 'ECBB'; Name: 'BandBattery2'),
(Id: 'ECBC'; Name: 'BandBattery3'),
(Id: 'ECBD'; Name: 'BandBattery4'),
(Id: 'ECBE'; Name: 'BandBattery5'),
(Id: 'ECBF'; Name: 'BandBattery6'),
(Id: 'ECC4'; Name: 'AddSurfaceHub'),
(Id: 'ECC5'; Name: 'DevUpdate'),
(Id: 'ECC6'; Name: 'Unit'),
(Id: 'ECC8'; Name: 'AddTo'),
(Id: 'ECC9'; Name: 'RemoveFrom'),
(Id: 'ECCA'; Name: 'RadioBtnOff'),
(Id: 'ECCB'; Name: 'RadioBtnOn'),
(Id: 'ECCC'; Name: 'RadioBullet2'),
(Id: 'ECCD'; Name: 'ExploreContent'),
(Id: 'ECE4'; Name: 'Blocked2'),
(Id: 'ECE7'; Name: 'ScrollMode'),
(Id: 'ECE8'; Name: 'ZoomMode'),
(Id: 'ECE9'; Name: 'PanMode'),
(Id: 'ECF0'; Name: 'WiredUSB'),
(Id: 'ECF1'; Name: 'WirelessUSB'),
(Id: 'ECF3'; Name: 'USBSafeConnect'),
(Id: 'ED0C'; Name: 'ActionCenterNotificationMirrored'),
(Id: 'ED0D'; Name: 'ActionCenterMirrored'),
(Id: 'ED0E'; Name: 'SubscriptionAdd'),
(Id: 'ED10'; Name: 'ResetDevice'),
(Id: 'ED11'; Name: 'SubscriptionAddMirrored'),
(Id: 'ED14'; Name: 'QRCode'),
(Id: 'ED15'; Name: 'Feedback'),
(Id: 'ED1E'; Name: 'Subtitles'),
(Id: 'ED1F'; Name: 'SubtitlesAudio'),
(Id: 'ED25'; Name: 'OpenFolderHorizontal'),
(Id: 'ED28'; Name: 'CalendarMirrored'),
(Id: 'ED2A'; Name: 'MobeSIM'),
(Id: 'ED2B'; Name: 'MobeSIMNoProfile'),
(Id: 'ED2C'; Name: 'MobeSIMLocked'),
(Id: 'ED2D'; Name: 'MobeSIMBusy'),
(Id: 'ED2E'; Name: 'SignalError'),
(Id: 'ED2F'; Name: 'StreamingEnterprise'),
(Id: 'ED30'; Name: 'Headphone0'),
(Id: 'ED31'; Name: 'Headphone1'),
(Id: 'ED32'; Name: 'Headphone2'),
(Id: 'ED33'; Name: 'Headphone3'),
(Id: 'ED35'; Name: 'Apps'),
(Id: 'ED39'; Name: 'KeyboardBrightness'),
(Id: 'ED3A'; Name: 'KeyboardLowerBrightness'),
(Id: 'ED3C'; Name: 'SkipBack10'),
(Id: 'ED3D'; Name: 'SkipForward30'),
(Id: 'ED41'; Name: 'TreeFolderFolder'),
(Id: 'ED42'; Name: 'TreeFolderFolderFill'),
(Id: 'ED43'; Name: 'TreeFolderFolderOpen'),
(Id: 'ED44'; Name: 'TreeFolderFolderOpenFill'),
(Id: 'ED47'; Name: 'MultimediaDMP'),
(Id: 'ED4C'; Name: 'KeyboardOneHanded'),
(Id: 'ED4D'; Name: 'Narrator'),
(Id: 'ED53'; Name: 'EmojiTabPeople'),
(Id: 'ED54'; Name: 'EmojiTabSmilesAnimals'),
(Id: 'ED55'; Name: 'EmojiTabCelebrationObjects'),
(Id: 'ED56'; Name: 'EmojiTabFoodPlants'),
(Id: 'ED57'; Name: 'EmojiTabTransitPlaces'),
(Id: 'ED58'; Name: 'EmojiTabSymbols'),
(Id: 'ED59'; Name: 'EmojiTabTextSmiles'),
(Id: 'ED5A'; Name: 'EmojiTabFavorites'),
(Id: 'ED5B'; Name: 'EmojiSwatch'),
(Id: 'ED5C'; Name: 'ConnectApp'),
(Id: 'ED5D'; Name: 'CompanionDeviceFramework'),
(Id: 'ED5E'; Name: 'Ruler'),
(Id: 'ED5F'; Name: 'FingerInking'),
(Id: 'ED60'; Name: 'StrokeErase'),
(Id: 'ED61'; Name: 'PointErase'),
(Id: 'ED62'; Name: 'ClearAllInk'),
(Id: 'ED63'; Name: 'Pencil'),
(Id: 'ED64'; Name: 'Marker'),
(Id: 'ED65'; Name: 'InkingCaret'),
(Id: 'ED66'; Name: 'InkingColorOutline'),
(Id: 'ED67'; Name: 'InkingColorFill'),
(Id: 'EDA2'; Name: 'HardDrive'),
(Id: 'EDA3'; Name: 'NetworkAdapter'),
(Id: 'EDA4'; Name: 'Touchscreen'),
(Id: 'EDA5'; Name: 'NetworkPrinter'),
(Id: 'EDA6'; Name: 'CloudPrinter'),
(Id: 'EDA7'; Name: 'KeyboardShortcut'),
(Id: 'EDA8'; Name: 'BrushSize'),
(Id: 'EDA9'; Name: 'NarratorForward'),
(Id: 'EDAA'; Name: 'NarratorForwardMirrored'),
(Id: 'EDAB'; Name: 'SyncBadge12'),
(Id: 'EDAC'; Name: 'RingerBadge12'),
(Id: 'EDAD'; Name: 'AsteriskBadge12'),
(Id: 'EDAE'; Name: 'ErrorBadge12'),
(Id: 'EDAF'; Name: 'CircleRingBadge12'),
(Id: 'EDB0'; Name: 'CircleFillBadge12'),
(Id: 'EDB1'; Name: 'ImportantBadge12'),
(Id: 'EDB3'; Name: 'MailBadge12'),
(Id: 'EDB4'; Name: 'PauseBadge12'),
(Id: 'EDB5'; Name: 'PlayBadge12'),
(Id: 'EDC6'; Name: 'PenWorkspace'),
(Id: 'EDD6'; Name: 'CaretRight8'),
(Id: 'EDD9'; Name: 'CaretLeftSolid8'),
(Id: 'EDDA'; Name: 'CaretRightSolid8'),
(Id: 'EDDB'; Name: 'CaretUpSolid8'),
(Id: 'EDDC'; Name: 'CaretDownSolid8'),
(Id: 'EDE1'; Name: 'Export'),
(Id: 'EDE2'; Name: 'ExportMirrored'),
(Id: 'EDE3'; Name: 'ButtonMenu'),
(Id: 'EDE4'; Name: 'CloudSeach'),
(Id: 'EDE5'; Name: 'PinyinIMELogo'),
(Id: 'EDFB'; Name: 'CalligraphyPen'),
(Id: 'EE35'; Name: 'ReplyMirrored'),
(Id: 'EE3F'; Name: 'LockscreenDesktop'),
(Id: 'EE40'; Name: 'TaskViewSettings'),
(Id: 'EE4A'; Name: 'Play36'),
(Id: 'EE56'; Name: 'PenPalette'),
(Id: 'EE57'; Name: 'GuestUser'),
(Id: 'EE63'; Name: 'SettingsBattery'),
(Id: 'EE64'; Name: 'TaskbarPhone'),
(Id: 'EE65'; Name: 'LockScreenGlance'),
(Id: 'EE6F'; Name: 'GenericScan'),
(Id: 'EE71'; Name: 'ImageExport'),
(Id: 'EE77'; Name: 'WifiEthernet'),
(Id: 'EE79'; Name: 'ActionCenterQuiet'),
(Id: 'EE7A'; Name: 'ActionCenterQuietNotification'),
(Id: 'EE92'; Name: 'TrackersMirrored'),
(Id: 'EE93'; Name: 'DateTimeMirrored'),
(Id: 'EE94'; Name: 'Wheel'),
(Id: 'EEA3'; Name: 'VirtualMachineGroup'),
(Id: 'EECA'; Name: 'ButtonView2'),
(Id: 'EF15'; Name: 'PenWorkspaceMirrored'),
(Id: 'EF16'; Name: 'PenPaletteMirrored'),
(Id: 'EF17'; Name: 'StrokeEraseMirrored'),
(Id: 'EF18'; Name: 'PointEraseMirrored'),
(Id: 'EF19'; Name: 'ClearAllInkMirrored'),
(Id: 'EF1F'; Name: 'BackgroundToggle'),
(Id: 'EF20'; Name: 'Marquee'),
(Id: 'EF2C'; Name: 'ChromeCloseContrast'),
(Id: 'EF2D'; Name: 'ChromeMinimizeContrast'),
(Id: 'EF2E'; Name: 'ChromeMaximizeContrast'),
(Id: 'EF2F'; Name: 'ChromeRestoreContrast'),
(Id: 'EF31'; Name: 'TrafficLight'),
(Id: 'EF3B'; Name: 'Replay'),
(Id: 'EF3C'; Name: 'Eyedropper'),
(Id: 'EF3D'; Name: 'LineDisplay'),
(Id: 'EF3E'; Name: 'PINPad'),
(Id: 'EF3F'; Name: 'SignatureCapture'),
(Id: 'EF40'; Name: 'ChipCardCreditCardReader'),
(Id: 'EF58'; Name: 'PlayerSettings'),
(Id: 'EF6B'; Name: 'LandscapeOrientation'),
(Id: 'EF90'; Name: 'Flow'),
(Id: 'EFA5'; Name: 'Touchpad'),
(Id: 'EFA9'; Name: 'Speech'),
(Id: 'F000'; Name: 'KnowledgeArticle'),
(Id: 'F003'; Name: 'Relationship'),
(Id: 'F080'; Name: 'DefaultAPN'),
(Id: 'F081'; Name: 'UserAPN'),
(Id: 'F085'; Name: 'DoublePinyin'),
(Id: 'F08C'; Name: 'BlueLight'),
(Id: 'F093'; Name: 'ButtonA'),
(Id: 'F094'; Name: 'ButtonB'),
(Id: 'F095'; Name: 'ButtonY'),
(Id: 'F096'; Name: 'ButtonX'),
(Id: 'F0AD'; Name: 'ArrowUp8'),
(Id: 'F0AE'; Name: 'ArrowDown8'),
(Id: 'F0AF'; Name: 'ArrowRight8'),
(Id: 'F0B0'; Name: 'ArrowLeft8'),
(Id: 'F0B2'; Name: 'QuarentinedItems'),
(Id: 'F0B3'; Name: 'QuarentinedItemsMirrored'),
(Id: 'F0B4'; Name: 'Protractor'),
(Id: 'F0B5'; Name: 'ChecklistMirrored'),
(Id: 'F0B6'; Name: 'StatusCircle7'),
(Id: 'F0B7'; Name: 'StatusCheckmark7'),
(Id: 'F0B8'; Name: 'StatusErrorCircle7'),
(Id: 'F0B9'; Name: 'Connected'),
(Id: 'F0C6'; Name: 'PencilFill'),
(Id: 'F0C7'; Name: 'CalligraphyFill'),
(Id: 'F0CA'; Name: 'QuarterStarLeft'),
(Id: 'F0CB'; Name: 'QuarterStarRight'),
(Id: 'F0CC'; Name: 'ThreeQuarterStarLeft'),
(Id: 'F0CD'; Name: 'ThreeQuarterStarRight'),
(Id: 'F0CE'; Name: 'QuietHoursBadge12'),
(Id: 'F0D2'; Name: 'BackMirrored'),
(Id: 'F0D3'; Name: 'ForwardMirrored'),
(Id: 'F0D5'; Name: 'ChromeBackContrast'),
(Id: 'F0D6'; Name: 'ChromeBackContrastMirrored'),
(Id: 'F0D7'; Name: 'ChromeBackToWindowContrast'),
(Id: 'F0D8'; Name: 'ChromeFullScreenContrast'),
(Id: 'F0E2'; Name: 'GridView'),
(Id: 'F0E3'; Name: 'ClipboardList'),
(Id: 'F0E4'; Name: 'ClipboardListMirrored'),
(Id: 'F0E5'; Name: 'OutlineQuarterStarLeft'),
(Id: 'F0E6'; Name: 'OutlineQuarterStarRight'),
(Id: 'F0E7'; Name: 'OutlineHalfStarLeft'),
(Id: 'F0E8'; Name: 'OutlineHalfStarRight'),
(Id: 'F0E9'; Name: 'OutlineThreeQuarterStarLeft'),
(Id: 'F0EA'; Name: 'OutlineThreeQuarterStarRight'),
(Id: 'F0EB'; Name: 'SpatialVolume0'),
(Id: 'F0EC'; Name: 'SpatialVolume1'),
(Id: 'F0ED'; Name: 'SpatialVolume2'),
(Id: 'F0EE'; Name: 'SpatialVolume3'),
(Id: 'F0F7'; Name: 'OutlineStarLeftHalf'),
(Id: 'F0F8'; Name: 'OutlineStarRightHalf'),
(Id: 'F0F9'; Name: 'ChromeAnnotateContrast'),
(Id: 'F0FB'; Name: 'DefenderBadge12'),
(Id: 'F103'; Name: 'DetachablePC'),
(Id: 'F108'; Name: 'LeftStick'),
(Id: 'F109'; Name: 'RightStick'),
(Id: 'F10A'; Name: 'TriggerLeft'),
(Id: 'F10B'; Name: 'TriggerRight'),
(Id: 'F10C'; Name: 'BumperLeft'),
(Id: 'F10D'; Name: 'BumperRight'),
(Id: 'F10E'; Name: 'Dpad'),
(Id: 'F110'; Name: 'EnglishPunctuation'),
(Id: 'F111'; Name: 'ChinesePunctuation'),
(Id: 'F119'; Name: 'HMD'),
(Id: 'F11B'; Name: 'CtrlSpatialRight'),
(Id: 'F126'; Name: 'PaginationDotOutline10'),
(Id: 'F127'; Name: 'PaginationDotSolid10'),
(Id: 'F128'; Name: 'StrokeErase2'),
(Id: 'F129'; Name: 'SmallErase'),
(Id: 'F12A'; Name: 'LargeErase'),
(Id: 'F12B'; Name: 'FolderHorizontal'),
(Id: 'F12E'; Name: 'MicrophoneListening'),
(Id: 'F12F'; Name: 'StatusExclamationCircle7'),
(Id: 'F131'; Name: 'Video360'),
(Id: 'F133'; Name: 'GiftboxOpen'),
(Id: 'F136'; Name: 'StatusCircleOuter'),
(Id: 'F137'; Name: 'StatusCircleInner'),
(Id: 'F138'; Name: 'StatusCircleRing'),
(Id: 'F139'; Name: 'StatusTriangleOuter'),
(Id: 'F13A'; Name: 'StatusTriangleInner'),
(Id: 'F13B'; Name: 'StatusTriangleExclamation'),
(Id: 'F13C'; Name: 'StatusCircleExclamation'),
(Id: 'F13D'; Name: 'StatusCircleErrorX'),
(Id: 'F13E'; Name: 'StatusCircleCheckmark'),
(Id: 'F13F'; Name: 'StatusCircleInfo'),
(Id: 'F140'; Name: 'StatusCircleBlock'),
(Id: 'F141'; Name: 'StatusCircleBlock2'),
(Id: 'F142'; Name: 'StatusCircleQuestionMark'),
(Id: 'F143'; Name: 'StatusCircleSync'),
(Id: 'F146'; Name: 'Dial1'),
(Id: 'F147'; Name: 'Dial2'),
(Id: 'F148'; Name: 'Dial3'),
(Id: 'F149'; Name: 'Dial4'),
(Id: 'F14A'; Name: 'Dial5'),
(Id: 'F14B'; Name: 'Dial6'),
(Id: 'F14C'; Name: 'Dial7'),
(Id: 'F14D'; Name: 'Dial8'),
(Id: 'F14E'; Name: 'Dial9'),
(Id: 'F14F'; Name: 'Dial10'),
(Id: 'F150'; Name: 'Dial11'),
(Id: 'F151'; Name: 'Dial12'),
(Id: 'F152'; Name: 'Dial13'),
(Id: 'F153'; Name: 'Dial14'),
(Id: 'F154'; Name: 'Dial15'),
(Id: 'F155'; Name: 'Dial16'),
(Id: 'F156'; Name: 'DialShape1'),
(Id: 'F157'; Name: 'DialShape2'),
(Id: 'F158'; Name: 'DialShape3'),
(Id: 'F159'; Name: 'DialShape4'),
(Id: 'F161'; Name: 'TollSolid'),
(Id: 'F163'; Name: 'TrafficCongestionSolid'),
(Id: 'F164'; Name: 'ExploreContentSingle'),
(Id: 'F165'; Name: 'CollapseContent'),
(Id: 'F166'; Name: 'CollapseContentSingle'),
(Id: 'F167'; Name: 'InfoSolid'),
(Id: 'F168'; Name: 'GroupList'),
(Id: 'F169'; Name: 'CaretBottomRightSolidCenter8'),
(Id: 'F16A'; Name: 'ProgressRingDots'),
(Id: 'F16B'; Name: 'Checkbox14'),
(Id: 'F16C'; Name: 'CheckboxComposite14'),
(Id: 'F16D'; Name: 'CheckboxIndeterminateCombo14'),
(Id: 'F16E'; Name: 'CheckboxIndeterminateCombo'),
(Id: 'F175'; Name: 'StatusPause7'),
(Id: 'F17F'; Name: 'CharacterAppearance'),
(Id: 'F180'; Name: 'Lexicon'),
(Id: 'F182'; Name: 'ScreenTime'),
(Id: 'F191'; Name: 'HeadlessDevice'),
(Id: 'F193'; Name: 'NetworkSharing'),
(Id: 'F19D'; Name: 'EyeGaze'),
(Id: 'F1AD'; Name: 'WindowsInsider'),
(Id: 'F1CB'; Name: 'ChromeSwitch'),
(Id: 'F1CC'; Name: 'ChromeSwitchContast'),
(Id: 'F1D8'; Name: 'StatusCheckmark'),
(Id: 'F1D9'; Name: 'StatusCheckmarkLeft'),
(Id: 'F20C'; Name: 'KeyboardLeftAligned'),
(Id: 'F20D'; Name: 'KeyboardRightAligned'),
(Id: 'F210'; Name: 'KeyboardSettings'),
(Id: 'F211'; Name: 'NetworkPhysical'),
(Id: 'F22C'; Name: 'IOT'),
(Id: 'F22E'; Name: 'UnknownMirrored'),
(Id: 'F246'; Name: 'ViewDashboard'),
(Id: 'F259'; Name: 'ExploitProtectionSettings'),
(Id: 'F260'; Name: 'KeyboardNarrow'),
(Id: 'F261'; Name: 'Keyboard12Key'),
(Id: 'F26B'; Name: 'KeyboardDock'),
(Id: 'F26C'; Name: 'KeyboardUndock'),
(Id: 'F26D'; Name: 'KeyboardLeftDock'),
(Id: 'F26E'; Name: 'KeyboardRightDock'),
(Id: 'F270'; Name: 'Ear'),
(Id: 'F271'; Name: 'PointerHand'),
(Id: 'F272'; Name: 'Bullseye'),
(Id: 'F2B7'; Name: 'LocaleLanguage'),
(Id: 'F32A'; Name: 'PassiveAuthentication'),
(Id: 'F384'; Name: 'NetworkOffline'),
(Id: 'F385'; Name: 'NetworkConnected'),
(Id: 'F386'; Name: 'NetworkConnectedCheckmark'),
(Id: 'F3B1'; Name: 'SignOut'),
(Id: 'F3CC'; Name: 'StatusInfo'),
(Id: 'F3CD'; Name: 'StatusInfoLeft'),
(Id: 'F3E2'; Name: 'NearbySharing'),
(Id: 'F3E7'; Name: 'CtrlSpatialLeft'),
(Id: 'F404'; Name: 'InteractiveDashboard'),
(Id: 'F406'; Name: 'ClippingTool'),
(Id: 'F407'; Name: 'RectangularClipping'),
(Id: 'F408'; Name: 'FreeFormClipping'),
(Id: 'F413'; Name: 'CopyTo'),
(Id: 'F439'; Name: 'DynamicLock'),
(Id: 'F45E'; Name: 'PenTips'),
(Id: 'F45F'; Name: 'PenTipsMirrored'),
(Id: 'F460'; Name: 'HWPJoin'),
(Id: 'F461'; Name: 'HWPInsert'),
(Id: 'F462'; Name: 'HWPStrikeThrough'),
(Id: 'F463'; Name: 'HWPScratchOut'),
(Id: 'F464'; Name: 'HWPSplit'),
(Id: 'F465'; Name: 'HWPNewLine'),
(Id: 'F466'; Name: 'HWPOverwrite'),
(Id: 'F473'; Name: 'MobWifiWarning1'),
(Id: 'F474'; Name: 'MobWifiWarning2'),
(Id: 'F475'; Name: 'MobWifiWarning3'),
(Id: 'F476'; Name: 'MobWifiWarning4'),
(Id: 'F49A'; Name: 'Globe2'),
(Id: 'F4A9'; Name: 'GIF'),
(Id: 'F4AA'; Name: 'Sticker2'),
(Id: 'F4BE'; Name: 'SurfaceHubSelected'),
(Id: 'F4BF'; Name: 'HoloLensSelected'),
(Id: 'F4C0'; Name: 'Earbud'),
(Id: 'F4C3'; Name: 'MixVolumes'),
(Id: 'F540'; Name: 'Safe'),
(Id: 'F552'; Name: 'LaptopSecure'),
(Id: 'F56D'; Name: 'PrintDefault'),
(Id: 'F56E'; Name: 'PageMirrored'),
(Id: 'F56F'; Name: 'LandscapeOrientationMirrored'),
(Id: 'F570'; Name: 'ColorOff'),
(Id: 'F571'; Name: 'PrintAllPages'),
(Id: 'F572'; Name: 'PrintCustomRange'),
(Id: 'F573'; Name: 'PageMarginPortraitNarrow'),
(Id: 'F574'; Name: 'PageMarginPortraitNormal'),
(Id: 'F575'; Name: 'PageMarginPortraitModerate'),
(Id: 'F576'; Name: 'PageMarginPortraitWide'),
(Id: 'F577'; Name: 'PageMarginLandscapeNarrow'),
(Id: 'F578'; Name: 'PageMarginLandscapeNormal'),
(Id: 'F579'; Name: 'PageMarginLandscapeModerate'),
(Id: 'F57A'; Name: 'PageMarginLandscapeWide'),
(Id: 'F57B'; Name: 'CollateLandscape'),
(Id: 'F57C'; Name: 'CollatePortrait'),
(Id: 'F57D'; Name: 'CollatePortraitSeparated'),
(Id: 'F57E'; Name: 'DuplexLandscapeOneSided'),
(Id: 'F57F'; Name: 'DuplexLandscapeOneSidedMirrored'),
(Id: 'F580'; Name: 'DuplexLandscapeTwoSidedLongEdge'),
(Id: 'F581'; Name: 'DuplexLandscapeTwoSidedLongEdgeMirrored'),
(Id: 'F582'; Name: 'DuplexLandscapeTwoSidedShortEdge'),
(Id: 'F583'; Name: 'DuplexLandscapeTwoSidedShortEdgeMirrored'),
(Id: 'F584'; Name: 'DuplexPortraitOneSided'),
(Id: 'F585'; Name: 'DuplexPortraitOneSidedMirrored'),
(Id: 'F586'; Name: 'DuplexPortraitTwoSidedLongEdge'),
(Id: 'F587'; Name: 'DuplexPortraitTwoSidedLongEdgeMirrored'),
(Id: 'F588'; Name: 'DuplexPortraitTwoSidedShortEdge'),
(Id: 'F589'; Name: 'DuplexPortraitTwoSidedShortEdgeMirrored'),
(Id: 'F58A'; Name: 'PPSOneLandscape'),
(Id: 'F58B'; Name: 'PPSTwoLandscape'),
(Id: 'F58C'; Name: 'PPSTwoPortrait'),
(Id: 'F58D'; Name: 'PPSFourLandscape'),
(Id: 'F58E'; Name: 'PPSFourPortrait'),
(Id: 'F58F'; Name: 'HolePunchOff'),
(Id: 'F590'; Name: 'HolePunchPortraitLeft'),
(Id: 'F591'; Name: 'HolePunchPortraitRight'),
(Id: 'F592'; Name: 'HolePunchPortraitTop'),
(Id: 'F593'; Name: 'HolePunchPortraitBottom'),
(Id: 'F594'; Name: 'HolePunchLandscapeLeft'),
(Id: 'F595'; Name: 'HolePunchLandscapeRight'),
(Id: 'F596'; Name: 'HolePunchLandscapeTop'),
(Id: 'F597'; Name: 'HolePunchLandscapeBottom'),
(Id: 'F598'; Name: 'StaplingOff'),
(Id: 'F599'; Name: 'StaplingPortraitTopLeft'),
(Id: 'F59A'; Name: 'StaplingPortraitTopRight'),
(Id: 'F59B'; Name: 'StaplingPortraitBottomRight'),
(Id: 'F59C'; Name: 'StaplingPortraitTwoLeft'),
(Id: 'F59D'; Name: 'StaplingPortraitTwoRight'),
(Id: 'F59E'; Name: 'StaplingPortraitTwoTop'),
(Id: 'F59F'; Name: 'StaplingPortraitTwoBottom'),
(Id: 'F5A0'; Name: 'StaplingPortraitBookBinding'),
(Id: 'F5A1'; Name: 'StaplingLandscapeTopLeft'),
(Id: 'F5A2'; Name: 'StaplingLandscapeTopRight'),
(Id: 'F5A3'; Name: 'StaplingLandscapeBottomLeft'),
(Id: 'F5A4'; Name: 'StaplingLandscapeBottomRight'),
(Id: 'F5A5'; Name: 'StaplingLandscapeTwoLeft'),
(Id: 'F5A6'; Name: 'StaplingLandscapeTwoRight'),
(Id: 'F5A7'; Name: 'StaplingLandscapeTwoTop'),
(Id: 'F5A8'; Name: 'StaplingLandscapeTwoBottom'),
(Id: 'F5A9'; Name: 'StaplingLandscapeBookBinding'),
(Id: 'F5AA'; Name: 'StatusDataTransferRoaming'),
(Id: 'F5AB'; Name: 'MobSIMError'),
(Id: 'F5AC'; Name: 'CollateLandscapeSeparated'),
(Id: 'F5AD'; Name: 'PPSOnePortrait'),
(Id: 'F5AE'; Name: 'StaplingPortraitBottomLeft'),
(Id: 'F5B0'; Name: 'PlaySolid'),
(Id: 'F5E7'; Name: 'RepeatOff'),
(Id: 'F5ED'; Name: 'Set'),
(Id: 'F5EE'; Name: 'SetSolid'),
(Id: 'F5EF'; Name: 'FuzzyReading'),
(Id: 'F5F2'; Name: 'VerticalBattery0'),
(Id: 'F5F3'; Name: 'VerticalBattery1'),
(Id: 'F5F4'; Name: 'VerticalBattery2'),
(Id: 'F5F5'; Name: 'VerticalBattery3'),
(Id: 'F5F6'; Name: 'VerticalBattery4'),
(Id: 'F5F7'; Name: 'VerticalBattery5'),
(Id: 'F5F8'; Name: 'VerticalBattery6'),
(Id: 'F5F9'; Name: 'VerticalBattery7'),
(Id: 'F5FA'; Name: 'VerticalBattery8'),
(Id: 'F5FB'; Name: 'VerticalBattery9'),
(Id: 'F5FC'; Name: 'VerticalBattery10'),
(Id: 'F5FD'; Name: 'VerticalBatteryCharging0'),
(Id: 'F5FE'; Name: 'VerticalBatteryCharging1'),
(Id: 'F5FF'; Name: 'VerticalBatteryCharging2'),
(Id: 'F600'; Name: 'VerticalBatteryCharging3'),
(Id: 'F601'; Name: 'VerticalBatteryCharging4'),
(Id: 'F602'; Name: 'VerticalBatteryCharging5'),
(Id: 'F603'; Name: 'VerticalBatteryCharging6'),
(Id: 'F604'; Name: 'VerticalBatteryCharging7'),
(Id: 'F605'; Name: 'VerticalBatteryCharging8'),
(Id: 'F606'; Name: 'VerticalBatteryCharging9'),
(Id: 'F607'; Name: 'VerticalBatteryCharging10'),
(Id: 'F608'; Name: 'VerticalBatteryUnknown'),
(Id: 'F614'; Name: 'DoublePortrait'),
(Id: 'F615'; Name: 'DoubleLandscape'),
(Id: 'F616'; Name: 'SinglePortrait'),
(Id: 'F617'; Name: 'SingleLandscape'),
(Id: 'F618'; Name: 'SIMError'),
(Id: 'F619'; Name: 'SIMMissing'),
(Id: 'F61A'; Name: 'SIMLock'),
(Id: 'F61B'; Name: 'eSIM'),
(Id: 'F61C'; Name: 'eSIMNoProfile'),
(Id: 'F61D'; Name: 'eSIMLocked'),
(Id: 'F61E'; Name: 'eSIMBusy'),
(Id: 'F61F'; Name: 'NoiseCancelation'),
(Id: 'F620'; Name: 'NoiseCancelationOff'),
(Id: 'F623'; Name: 'MusicSharing'),
(Id: 'F624'; Name: 'MusicSharingOff'),
(Id: 'F63C'; Name: 'CircleShapeSolid'),
(Id: 'F657'; Name: 'WifiCallBars'),
(Id: 'F658'; Name: 'WifiCall0'),
(Id: 'F659'; Name: 'WifiCall1'),
(Id: 'F65A'; Name: 'WifiCall2'),
(Id: 'F65B'; Name: 'WifiCall3'),
(Id: 'F65C'; Name: 'WifiCall4'),
(Id: 'F69E'; Name: 'CHTLanguageBar'),
(Id: 'F6BA'; Name: 'EmojiTabMoreSymbols'),
(Id: 'F6FA'; Name: 'WebSearch'),
(Id: 'F712'; Name: 'Kiosk'),
(Id: 'F714'; Name: 'RTTLogo'),
(Id: 'F715'; Name: 'VoiceCall'),
(Id: 'F716'; Name: 'GoToMessage'),
(Id: 'F71A'; Name: 'ReturnToCall'),
(Id: 'F71C'; Name: 'StartPresenting'),
(Id: 'F71D'; Name: 'StopPresenting'),
(Id: 'F71E'; Name: 'ProductivityMode'),
(Id: 'F738'; Name: 'SetHistoryStatus'),
(Id: 'F739'; Name: 'SetHistoryStatus2'),
(Id: 'F73D'; Name: 'Keyboardsettings20'),
(Id: 'F73E'; Name: 'OneHandedRight20'),
(Id: 'F73F'; Name: 'OneHandedLeft20'),
(Id: 'F740'; Name: 'Split20'),
(Id: 'F741'; Name: 'Full20'),
(Id: 'F742'; Name: 'Handwriting20'),
(Id: 'F743'; Name: 'CheveronLeft20'),
(Id: 'F744'; Name: 'CheveronLeft32'),
(Id: 'F745'; Name: 'CheveronRight20'),
(Id: 'F746'; Name: 'CheveronRight32'),
(Id: 'F781'; Name: 'MicOff2'),
(Id: 'F785'; Name: 'DeliveryOptimization'),
(Id: 'F78A'; Name: 'CancelMedium'),
(Id: 'F78B'; Name: 'SearchMedium'),
(Id: 'F78C'; Name: 'AcceptMedium'),
(Id: 'F78D'; Name: 'RevealPasswordMedium'),
(Id: 'F7AD'; Name: 'DeleteWord'),
(Id: 'F7AE'; Name: 'DeleteWordFill'),
(Id: 'F7AF'; Name: 'DeleteLines'),
(Id: 'F7B0'; Name: 'DeleteLinesFill'),
(Id: 'F7B1'; Name: 'InstertWords'),
(Id: 'F7B2'; Name: 'InstertWordsFill'),
(Id: 'F7B3'; Name: 'JoinWords'),
(Id: 'F7B4'; Name: 'JoinWordsFill'),
(Id: 'F7B5'; Name: 'OverwriteWords'),
(Id: 'F7B6'; Name: 'OverwriteWordsFill'),
(Id: 'F7B7'; Name: 'AddNewLine'),
(Id: 'F7B8'; Name: 'AddNewLineFill'),
(Id: 'F7B9'; Name: 'OverwriteWordsKorean'),
(Id: 'F7BA'; Name: 'OverwriteWordsFillKorean'),
(Id: 'F7BB'; Name: 'EducationIcon'),
(Id: 'F7ED'; Name: 'WindowSnipping'),
(Id: 'F7EE'; Name: 'VideoCapture'),
(Id: 'F809'; Name: 'StatusSecured'),
(Id: 'F83B'; Name: 'NarratorApp'),
(Id: 'F83D'; Name: 'PowerButtonUpdate'),
(Id: 'F83E'; Name: 'RestartUpdate'),
(Id: 'F83F'; Name: 'UpdateStatusDot'),
(Id: 'F847'; Name: 'Eject')
);
{$ENDREGION}

procedure TFormIcons.ButtonCancelClick(Sender: TObject);
begin
  Close;
end;

procedure TFormIcons.ButtonOkClick(Sender: TObject);
begin
  Close;
end;

function TFormIcons.FindIconIndex(const IconCode: string): Integer;
var
  I: Integer;
begin
  Result := -1;
  if IconCode <> '' then
  begin
    for I := Low(IconChars) to High(IconChars) do
    begin
      if StrToInt('$' + IconChars[I].Id) = Ord(IconCode[1]) then
        Exit(I);
    end;
  end;
end;

procedure TFormIcons.FormResize(Sender: TObject);
var
  NumIcons: Integer;
  Selection: TGridRect;
  SelectionIndex: Integer;
begin
  NumIcons := Length(IconChars);
  GridIcons.ColCount := GridIcons.Width div GridIcons.DefaultColWidth - 1;
  GridIcons.RowCount := NumIcons div GridIcons.ColCount;//GridIcons.Height div GridIcons.DefaultRowHeight;

  SelectionIndex := FindIconIndex(FIconCode);
  if SelectionIndex >= 0 then
  begin
    Selection.Left := SelectionIndex mod GridIcons.ColCount;
    Selection.Top := SelectionIndex div GridIcons.ColCount;
    Selection.Right := SelectionIndex mod GridIcons.ColCount;
    Selection.Bottom := SelectionIndex div GridIcons.ColCount;
    GridIcons.Selection := Selection;
    GridIconsClick(GridIcons);
  end;

  GridIcons.Invalidate;
end;

procedure TFormIcons.FormShow(Sender: TObject);
var
  Selection: TGridRect;
  SelectionIndex: Integer;
begin
  if FIconCode <> '' then
  begin
    EditIconCode.Text := IntToHex(Ord(FIconCode[1]));
  end;

  SelectionIndex := FindIconIndex(FIconCode);
  if SelectionIndex >= 0 then
  begin
    Selection.Left := SelectionIndex mod GridIcons.ColCount;
    Selection.Top := SelectionIndex div GridIcons.ColCount;
    Selection.Right := SelectionIndex mod GridIcons.ColCount;
    Selection.Bottom := SelectionIndex div GridIcons.ColCount;
    GridIcons.Selection := Selection;
    GridIcons.TopRow := SelectionIndex div GridIcons.ColCount;
    GridIconsClick(GridIcons);
    GridIcons.SetFocus;
  end;
end;

procedure TFormIcons.GridIconsClick(Sender: TObject);
var
  CharIndex: Integer;
  CharCode: Integer;
begin
  CharIndex := GridIcons.Selection.Left + GridIcons.Selection.Top * GridIcons.ColCount;
  if CharIndex < Length(IconChars) then
  begin
    LabelIconDescription.Caption := IconChars[CharIndex].Name;
    EditIconCode.Text := IconChars[CharIndex].Id;
  end;

  CharCode := StrToInt('$' + EditIconCode.Text);
  FIconCode := Chr(CharCode);
end;

procedure TFormIcons.GridIconsDblClick(Sender: TObject);
begin
  ButtonOk.Click;
end;

procedure TFormIcons.GridIconsDrawCell(Sender: TObject; ACol, ARow: Integer; Rect:
    TRect; State: TGridDrawState);
var
  CharIndex: Integer;
  CharCode: Integer;
begin
  if gdSelected in State then
    GridIcons.Canvas.Brush.Color := TColors.Lightgrey
  else
    GridIcons.Canvas.Brush.Color := TColors.SysWindow;
  GridIcons.Canvas.FillRect(Rect);
  if (gdFocused in State) then
  begin
    GridIcons.Canvas.DrawFocusRect(Rect);
  end;


  CharIndex := ACol + ARow * GridIcons.ColCount;
  if CharIndex < Length(IconChars) then
  begin
    CharCode := StrToInt('$' + IconChars[CharIndex].Id);
    GridIcons.Canvas.Font := GridIcons.Font;
    GridIcons.Canvas.Font.Color := clWindowText;
    GridIcons.Canvas.TextRect(Rect, Rect.Left + 2, Rect.Top + 2, Chr(CharCode));
    GridIcons.Canvas.Font.Name := Font.Name;
    GridIcons.Canvas.Font.Size := 8;
    GridIcons.Canvas.Font.Color := clGrayText;
    GridIcons.Canvas.TextOut(Rect.Left + 30, Rect.Top + 5, IconChars[CharIndex].Id);
  end;
end;

{ TSymbolCharProperty }

procedure TSymbolCharProperty.Edit;
var
  FormIcons: TFormIcons;
begin
  inherited;
  FormIcons := TFormIcons.Create (Application);
  try
    FormIcons.IconCode := GetStrValue;
    if FormIcons.ShowModal = mrOK then
      SetStrValue(FormIcons.IconCode);
  finally
    FormIcons.Free;
  end;
end;

function TSymbolCharProperty.GetAttributes: TPropertyAttributes;
begin
  Result := [paDialog];
end;

function TSymbolCharProperty.GetValue: string;
var
  Value: string;
begin
  Value := GetStrValue;
  if Value <> '' then
    Result := IntToHex(Ord(Value[1]))
  else
    Result := '';
end;

procedure TSymbolCharProperty.SetValue(const Value: string);
begin
  if TRegEx.IsMatch(Value, '[a-fA-F0-9]+') then
  begin
    if Value <> '' then
      SetStrValue(Chr(StrToInt('$' + Value)))
    else
      SetStrValue(Value);
  end
  else
    SetStrValue(Value);
end;

end.
