unit UCL.Colors;

interface

uses
  Graphics;

var
  SCROLLBOX_BACK_NIL, SCROLLBOX_BACK_LIGHT, SCROLLBOX_BACK_DARK: TColor;

  PANEL_BACK_LIGHT, PANEL_BACK_DARK: TColor;

  TOOLTIP_BACK_LIGHT, TOOLTIP_BACK_DARK: TColor;
  TOOLTIP_BORDER_LIGHT, TOOLTIP_BORDER_DARK: TColor;

  TEXT_DISABLED: TColor;

  CAPTION_BACK_LIGHT, CAPTION_BACK_DARK: TColor;

  FORM_BACK_LIGHT, FORM_BACK_DARK: TColor;

implementation

initialization
  SCROLLBOX_BACK_NIL := $E6E6E6;
  SCROLLBOX_BACK_LIGHT := $E6E6E6;
  SCROLLBOX_BACK_DARK := $1F1F1F;

  PANEL_BACK_LIGHT := $E6E6E6;
  PANEL_BACK_DARK := $1F1F1F;

  TOOLTIP_BACK_LIGHT := $F2F2F2;
  TOOLTIP_BACK_DARK := $2B2B2B;
  TOOLTIP_BORDER_LIGHT := $CCCCCC;
  TOOLTIP_BORDER_DARK := $767676;

  TEXT_DISABLED := $666666;

  CAPTION_BACK_LIGHT := $F2F2F2;
  CAPTION_BACK_DARK := $2B2B2B;

  FORM_BACK_LIGHT := $FFFFFF;
  FORM_BACK_DARK := $000000;
end.
